[package]
name = "ez-gfx-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-artifact.workspace = true
ez-gfx-hal.workspace = true
ez-gfx-texture-manager.workspace = true
blake3.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
arrayvec.workspace = true
smallvec.workspace = true
compact_str.workspace = true

[lints]
workspace = true
