[package]
name = "ez-gfx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
basis = ["ez-gfx-runtime/basis"]
ffi = []
ktx2 = ["ez-gfx-runtime/ktx2"]

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true
ez-gfx-runtime.workspace = true
ez-gfx-artifact.workspace = true
blake3.workspace = true
bytemuck.workspace = true
ez-gfx-assets = { path = "../ez-gfx-assets" }
crossbeam-channel.workspace = true
ez-gfx-backend-vulkan = { path = "../ez-gfx-backend-vulkan" }

raw-window-handle.workspace = true
thiserror.workspace = true
smallvec.workspace = true
arrayvec.workspace = true
compact_str.workspace = true

[dev-dependencies]
static_assertions.workspace = true
[target.'cfg(windows)'.dependencies]
ez-gfx-backend-dx12 = { path = "../ez-gfx-backend-dx12" }

[target.'cfg(target_vendor = "apple")'.dependencies]
ez-gfx-backend-metal = { path = "../ez-gfx-backend-metal" }

[lints]
workspace = true
