[package]
name = "ez-gfx-geometry-manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true

[lints]
workspace = true

[dev-dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true
