[package]
name = "ez-gfx-geometry-manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Backend-neutral vertex and index heap allocation and upload policy for ez-gfx"
homepage.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true

[lints]
workspace = true

[dev-dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true
