//! Rust-to-XML and XML-to-C binding generation.
mod header;

use header::{parse_xml, render_header};

use anyhow::{Context, Result, anyhow, bail};
use quick_xml::{
    Writer,
    events::{BytesDecl, BytesEnd, BytesStart, BytesText, Event},
};
use serde::Deserialize;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};
use syn::{Attribute, Expr, Fields, FnArg, Item, Lit, Meta, Pat, ReturnType, Type, Visibility};

/// Notice prepended to generated XML.
pub const XML_NOTICE: &str = "<!-- Generated by tools/bindgen from crates/ez-gfx-ffi. Do not edit; update Rust declarations/docs or binding metadata. -->";
/// Notice prepended to the generated C header.
pub const HEADER_NOTICE: &str = "/* Generated by tools/bindgen from bindings/bindings.xml. Do not edit; update crates/ez-gfx-ffi or tools/bindgen. */";

#[derive(Debug, Default, Deserialize)]
struct Metadata {
    root: BTreeMap<String, String>,
    items: BTreeMap<String, MetaItem>,
}
#[derive(Debug, Default, Deserialize)]
struct MetaItem {
    #[serde(default)]
    attrs: BTreeMap<String, String>,
    #[serde(default)]
    children: BTreeMap<String, BTreeMap<String, String>>,
    #[serde(default)]
    child_order: Vec<String>,
}
#[derive(Clone, Debug)]
struct Decl {
    name: String,
    doc: String,
    returns_doc: String,
    returns_seen: bool,
    attrs: BTreeMap<String, String>,
    child_attrs: BTreeMap<String, BTreeMap<String, String>>,
    child_order: Vec<String>,
    children: Vec<Child>,
}
#[derive(Clone, Debug)]
struct Child {
    name: String,
    doc: String,
    attrs: BTreeMap<String, String>,
    value: Option<String>,
}
#[derive(Default)]
struct Contract {
    abi: String,
    handles: Vec<Decl>,
    enums: Vec<Decl>,
    structs: Vec<Decl>,
    callbacks: Vec<Decl>,
    functions: Vec<Decl>,
}

/// Returns the workspace root containing this tool.
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Parses authoritative FFI Rust declarations and renders XML.
///
/// # Errors
///
/// Returns an error for malformed source or metadata and unsupported declarations.
pub fn generate_xml(root: &Path) -> Result<String> {
    let source_root = root.join("crates/ez-gfx-ffi/src");
    let metadata: Metadata = serde_json::from_str(
        &fs::read_to_string(source_root.join("bindings-metadata.json"))
            .context("read binding metadata")?,
    )
    .context("parse binding metadata")?;
    let mut contract = parse_rust(&source_root, &metadata)?;
    contract.abi = find_abi(&source_root.join("lib.rs"))?;
    render_xml(&contract, &metadata.root)
}

/// Parses validated bindings XML and renders a portable C header.
///
/// # Errors
///
/// Returns an error when XML is malformed, incomplete, or cannot be rendered.
pub fn generate_header(xml: &str) -> Result<String> {
    render_header(&parse_xml(xml)?)
}

/// Generates selected outputs under `root`.
///
/// # Errors
///
/// Returns an error when generation, validation, or atomic output replacement fails.
pub fn write_generated(root: &Path, xml: bool, header: bool) -> Result<()> {
    if !xml && !header {
        bail!("at least one output must be selected");
    }
    if xml {
        let output = generate_xml(root)?;
        write_checked(&root.join("bindings/bindings.xml"), &output)?;
    }
    if header {
        let input =
            fs::read_to_string(root.join("bindings/bindings.xml")).context("read bindings XML")?;
        let output = generate_header(&input)?;
        write_checked(&root.join("bindings/c/include/ez_gfx_api.h"), &output)?;
    }
    Ok(())
}

fn write_checked(path: &Path, contents: &str) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("output path has no parent: {}", path.display()))?;
    fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, contents).with_context(|| format!("write {}", temporary.display()))?;
    fs::rename(&temporary, path).with_context(|| format!("replace {}", path.display()))
}

fn parse_rust(dir: &Path, metadata: &Metadata) -> Result<Contract> {
    let mut files = Vec::new();
    collect_rs(dir, &mut files)?;
    files.sort();
    let mut contract = Contract::default();
    let mut names = BTreeSet::new();
    for path in files {
        let input =
            fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let file = syn::parse_file(&input).with_context(|| format!("parse {}", path.display()))?;
        for item in file.items {
            parse_item(item, metadata, &mut contract, &mut names)?;
        }
    }
    validate_metadata(metadata, &contract)?;
    Ok(contract)
}

// Every metadata key must match a parsed Rust declaration, and every child key
// must match a parsed field, variant, or parameter; anything else is stale
// metadata left behind by a rename or removal.
fn validate_metadata(metadata: &Metadata, contract: &Contract) -> Result<()> {
    let all: Vec<(&str, &Decl)> = [
        ("handle", contract.handles.as_slice()),
        ("enum", contract.enums.as_slice()),
        ("struct", contract.structs.as_slice()),
        ("callback", contract.callbacks.as_slice()),
        ("function", contract.functions.as_slice()),
    ]
    .into_iter()
    .flat_map(|(kind, declarations)| {
        declarations
            .iter()
            .map(move |declaration| (kind, declaration))
    })
    .collect();
    let mut used = BTreeSet::new();
    for (kind, declaration) in &all {
        let key = format!("{kind}:{}", declaration.name);
        let Some(meta) = metadata.items.get(&key) else {
            if *kind == "callback" {
                continue;
            }
            bail!("missing binding metadata for {key}");
        };
        used.insert(key);
        let children: BTreeSet<&str> = declaration
            .children
            .iter()
            .map(|child| child.name.as_str())
            .collect();
        for child_key in meta.children.keys() {
            if !children.contains(child_key.as_str()) {
                bail!(
                    "stale binding metadata child {child_key} for {kind} {}",
                    declaration.name
                );
            }
        }
        if !meta.child_order.is_empty() {
            let order: BTreeSet<&str> = meta.child_order.iter().map(String::as_str).collect();
            if order != children {
                bail!(
                    "binding metadata child order for {kind} {} does not match parsed children",
                    declaration.name
                );
            }
        }
    }
    for key in metadata.items.keys() {
        if !used.contains(key) {
            bail!("stale binding metadata for {key}");
        }
    }
    Ok(())
}

fn collect_rs(dir: &Path, output: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
        let path = entry?.path();
        if path.is_dir() {
            collect_rs(&path, output)?;
        } else if path.extension().is_some_and(|value| value == "rs") {
            output.push(path);
        }
    }
    Ok(())
}

fn parse_item(
    item: Item,
    metadata: &Metadata,
    contract: &mut Contract,
    names: &mut BTreeSet<String>,
) -> Result<()> {
    match item {
        Item::Type(item) if public(&item.vis) && item.ident.to_string().starts_with("EzGfx") => {
            let name = item.ident.to_string();
            if is_callback(&item.ty) {
                let mut declaration = declaration("callback", name, docs(&item.attrs), metadata)?;
                declaration
                    .attrs
                    .entry("return".into())
                    .or_insert_with(|| callback_return(&item.ty).unwrap_or_else(|| "void".into()));
                declaration.children = callback_parameters(&item.ty, &declaration)?;
                contract.callbacks.push(declaration);
            } else if name != "EzGfxHandle"
                && matches!(rust_type(&item.ty).as_str(), "uint64_t" | "EzGfxHandle")
            {
                insert_name(names, "handle", &name)?;
                contract
                    .handles
                    .push(declaration("handle", name, docs(&item.attrs), metadata)?);
            }
        }
        Item::Enum(item) if public(&item.vis) && has_repr(&item.attrs, "u8") => {
            let name = item.ident.to_string();
            insert_name(names, "enum", &name)?;
            let mut declaration = declaration("enum", name.clone(), docs(&item.attrs), metadata)?;
            declaration
                .attrs
                .entry("underlying".into())
                .or_insert_with(|| "uint8_t".into());
            for variant in item.variants {
                let value = match variant.discriminant {
                    Some((_, Expr::Lit(expr))) => match expr.lit {
                        Lit::Int(value) => value.base10_digits().to_owned(),
                        _ => bail!("non-integer discriminant in {name}"),
                    },
                    Some(_) => bail!("non-literal discriminant in {name}"),
                    None => bail!("implicit discriminant in {name}"),
                };
                let generated_name = format!("{name}_{}", variant.ident);
                let (mut attrs, _) = child_metadata(&declaration, &generated_name)?;
                attrs.remove("doc");
                declaration.children.push(Child {
                    name: generated_name,
                    doc: docs(&variant.attrs),
                    attrs,
                    value: Some(value),
                });
            }
            contract.enums.push(declaration);
        }
        Item::Struct(item) if public(&item.vis) && has_repr(&item.attrs, "C") => {
            let name = item.ident.to_string();
            insert_name(names, "struct", &name)?;
            let mut declaration = declaration("struct", name.clone(), docs(&item.attrs), metadata)?;
            let Fields::Named(fields) = item.fields else {
                bail!("binding struct {name} must have named fields");
            };
            for field in fields.named {
                let field_name = field
                    .ident
                    .ok_or_else(|| anyhow!("unnamed field in {name}"))?
                    .to_string();
                let (mut attrs, _) = child_metadata(&declaration, &field_name)?;
                attrs.remove("doc");
                let (ty, extent) = rust_field_type(&field.ty)?;
                attrs.entry("type".into()).or_insert(ty);
                if let Some(extent) = extent {
                    attrs.entry("array-length".into()).or_insert(extent);
                }
                declaration.children.push(Child {
                    name: field_name,
                    doc: docs(&field.attrs),
                    attrs,
                    value: None,
                });
            }
            contract.structs.push(declaration);
        }
        Item::Fn(item)
            if public(&item.vis)
                && item.sig.abi.as_ref().is_some_and(|abi| {
                    abi.name.as_ref().is_some_and(|name| name.value() == "C")
                })
                && item.sig.ident.to_string().starts_with("ez_gfx_") =>
        {
            let name = item.sig.ident.to_string();
            insert_name(names, "function", &name)?;
            let mut declaration =
                declaration("function", name.clone(), docs(&item.attrs), metadata)?;
            declaration
                .attrs
                .entry("return".into())
                .or_insert_with(|| match &item.sig.output {
                    ReturnType::Default => "void".into(),
                    ReturnType::Type(_, ty) => rust_type(ty),
                });
            for argument in item.sig.inputs {
                let FnArg::Typed(argument) = argument else {
                    bail!("method receiver in {name}");
                };
                let Pat::Ident(pat) = *argument.pat else {
                    bail!("non-identifier parameter in {name}");
                };
                let param_name = pat.ident.to_string();
                let (mut attrs, metadata_doc) = child_metadata(&declaration, &param_name)?;
                attrs.remove("doc");
                attrs
                    .entry("type".into())
                    .or_insert_with(|| rust_type(&argument.ty));
                declaration.children.push(Child {
                    name: param_name,
                    doc: metadata_doc,
                    attrs,
                    value: None,
                });
            }
            contract.functions.push(declaration);
        }
        _ => {}
    }
    Ok(())
}

fn declaration(kind: &str, name: String, doc: String, metadata: &Metadata) -> Result<Decl> {
    let meta = metadata.items.get(&format!("{kind}:{name}"));
    if meta.is_none() && kind != "callback" {
        bail!("missing binding metadata for {kind} {name}");
    }
    let mut attrs = meta.map_or_else(BTreeMap::new, |value| value.attrs.clone());
    let returns_doc = attrs.remove("returns-doc").unwrap_or_default();
    Ok(Decl {
        name,
        doc,
        returns_seen: !returns_doc.is_empty(),
        returns_doc,
        attrs,
        child_attrs: meta.map_or_else(BTreeMap::new, |value| value.children.clone()),
        child_order: meta.map_or_else(Vec::new, |value| value.child_order.clone()),
        children: Vec::new(),
    })
}

fn child_metadata(
    declaration: &Decl,
    source_name: &str,
) -> Result<(BTreeMap<String, String>, String)> {
    if !declaration.child_order.is_empty()
        && !declaration
            .child_order
            .iter()
            .any(|name| name == source_name)
    {
        bail!(
            "binding metadata for {} has no child named {source_name}",
            declaration.name
        );
    }
    let attrs = declaration
        .child_attrs
        .get(source_name)
        .cloned()
        .unwrap_or_default();
    let doc = attrs.get("doc").cloned().unwrap_or_default();
    Ok((attrs, doc))
}

fn insert_name(names: &mut BTreeSet<String>, kind: &str, name: &str) -> Result<()> {
    if !names.insert(format!("{kind}:{name}")) {
        bail!("duplicate {kind} declaration {name}");
    }
    Ok(())
}
fn public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}
fn has_repr(attrs: &[Attribute], wanted: &str) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("repr")
            && attr
                .parse_args::<syn::Ident>()
                .is_ok_and(|ident| ident == wanted)
    })
}
fn docs(attrs: &[Attribute]) -> String {
    let mut lines = Vec::new();
    for attr in attrs {
        if attr.path().is_ident("doc") {
            if let Meta::NameValue(value) = &attr.meta {
                if let Expr::Lit(expr) = &value.value {
                    if let Lit::Str(value) = &expr.lit {
                        lines.push(value.value().trim().to_owned());
                    }
                }
            }
        }
    }
    lines
        .into_iter()
        .take_while(|line| !line.starts_with('#'))
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}
fn rust_field_type(ty: &Type) -> Result<(String, Option<String>)> {
    if let Type::Array(array) = ty {
        let extent = match &array.len {
            Expr::Lit(expr) => match &expr.lit {
                Lit::Int(value) => value.base10_digits().to_owned(),
                _ => bail!("array extent is not integer"),
            },
            _ => bail!("array extent is not literal"),
        };
        Ok((rust_type(&array.elem), Some(extent)))
    } else {
        Ok((rust_type(ty), None))
    }
}
fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Path(path) => {
            let Some(segment) = path.path.segments.last() else {
                return "unsupported".into();
            };
            let ident = &segment.ident;
            if ident == "u8" {
                "uint8_t".into()
            } else if ident == "u16" {
                "uint16_t".into()
            } else if ident == "u32" {
                "uint32_t".into()
            } else if ident == "u64" {
                "uint64_t".into()
            } else if ident == "i32" {
                "int32_t".into()
            } else if ident == "f32" {
                "float".into()
            } else if ident == "usize" {
                "size_t".into()
            } else if ident == "c_void" {
                "void".into()
            } else {
                ident.to_string()
            }
        }
        Type::Ptr(ptr) => format!(
            "{}{} *",
            if ptr.const_token.is_some() {
                "const "
            } else {
                ""
            },
            rust_type(&ptr.elem)
        ),
        Type::Tuple(tuple) if tuple.elems.is_empty() => "void".into(),
        _ => "unsupported".into(),
    }
}
fn is_callback(ty: &Type) -> bool {
    callback_bare_fn(ty).is_some()
}
fn callback_bare_fn(ty: &Type) -> Option<&syn::TypeBareFn> {
    let Type::Path(path) = ty else { return None };
    let segment = path.path.segments.last()?;
    if segment.ident != "Option" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    let syn::GenericArgument::Type(Type::BareFn(function)) = args.args.first()? else {
        return None;
    };
    Some(function)
}
fn callback_return(ty: &Type) -> Option<String> {
    let function = callback_bare_fn(ty)?;
    Some(match &function.output {
        ReturnType::Default => "void".into(),
        ReturnType::Type(_, ty) => rust_type(ty),
    })
}
fn callback_parameters(ty: &Type, declaration: &Decl) -> Result<Vec<Child>> {
    let function =
        callback_bare_fn(ty).ok_or_else(|| anyhow!("invalid callback {}", declaration.name))?;
    Ok(function
        .inputs
        .iter()
        .enumerate()
        .map(|(index, input)| Child {
            name: input
                .name
                .as_ref()
                .map_or_else(|| format!("arg{}", index + 1), |(name, _)| name.to_string()),
            doc: String::new(),
            attrs: BTreeMap::from([("type".into(), rust_type(&input.ty))]),
            value: None,
        })
        .collect())
}
fn find_abi(path: &Path) -> Result<String> {
    let file = syn::parse_file(&fs::read_to_string(path)?)?;
    for item in file.items {
        if let Item::Const(value) = item {
            if value.ident == "EZ_GFX_ABI_VERSION" {
                if let Expr::Lit(expr) = *value.expr {
                    if let Lit::Int(value) = expr.lit {
                        return Ok(value.base10_digits().into());
                    }
                }
            }
        }
    }
    bail!("EZ_GFX_ABI_VERSION must be an integer literal")
}

fn xml_attr(element: &mut BytesStart<'_>, key: &str, value: &str) {
    element.push_attribute((key, value));
}
fn render_xml(contract: &Contract, root_meta: &BTreeMap<String, String>) -> Result<String> {
    let mut writer = Writer::new_with_indent(Vec::new(), b' ', 2);
    writer.write_event(Event::Decl(BytesDecl::new("1.0", Some("utf-8"), None)))?;
    let mut root = BytesStart::new("ez-gfx-bindings");
    xml_attr(
        &mut root,
        "version",
        root_meta.get("version").map_or("1", String::as_str),
    );
    xml_attr(&mut root, "abi-version", &contract.abi);
    xml_attr(
        &mut root,
        "library",
        root_meta
            .get("library")
            .map_or("ez_gfx_ffi", String::as_str),
    );
    writer.write_event(Event::Start(root))?;
    writer.write_event(Event::Start(BytesStart::new("description")))?;
    writer.write_event(Event::Text(BytesText::new(
        "Public EzGfx C ABI generated from ez-gfx-ffi Rust declarations and documentation.",
    )))?;
    writer.write_event(Event::End(BytesEnd::new("description")))?;
    write_section(&mut writer, "handles", "handle", &contract.handles, "value")?;
    write_section(&mut writer, "enums", "enum", &contract.enums, "value")?;
    write_section(&mut writer, "structs", "struct", &contract.structs, "field")?;
    write_section(
        &mut writer,
        "callbacks",
        "callback",
        &contract.callbacks,
        "param",
    )?;
    write_section(
        &mut writer,
        "functions",
        "function",
        &contract.functions,
        "param",
    )?;
    writer.write_event(Event::End(BytesEnd::new("ez-gfx-bindings")))?;
    let body = String::from_utf8(writer.into_inner())?;
    Ok(format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n{XML_NOTICE}\n{}\n",
        body.lines().skip(1).collect::<Vec<_>>().join("\n")
    ))
}
fn write_section(
    writer: &mut Writer<Vec<u8>>,
    section: &str,
    item_tag: &str,
    items: &[Decl],
    child_tag: &str,
) -> Result<()> {
    writer.write_event(Event::Start(BytesStart::new(section)))?;
    for item in items {
        let mut start = BytesStart::new(item_tag);
        xml_attr(&mut start, "name", &item.name);
        for (key, value) in &item.attrs {
            xml_attr(&mut start, key, value);
        }
        if !item.doc.is_empty() {
            xml_attr(&mut start, "doc", &item.doc);
        }
        if item.children.is_empty() && item_tag != "function" {
            writer.write_event(Event::Empty(start))?;
            continue;
        }

        writer.write_event(Event::Start(start))?;
        for child in &item.children {
            let mut element = BytesStart::new(child_tag);
            xml_attr(&mut element, "name", &child.name);
            if let Some(value) = &child.value {
                xml_attr(&mut element, "value", value);
            }
            for (key, value) in &child.attrs {
                xml_attr(&mut element, key, value);
            }
            if !child.doc.is_empty() {
                xml_attr(&mut element, "doc", &child.doc);
            }
            writer.write_event(Event::Empty(element))?;
        }
        if item_tag == "function" && item.returns_seen {
            let mut returns = BytesStart::new("returns");
            if !item.returns_doc.is_empty() {
                xml_attr(&mut returns, "doc", &item.returns_doc);
            }
            writer.write_event(Event::Empty(returns))?;
        }
        writer.write_event(Event::End(BytesEnd::new(item_tag)))?;
    }
    writer.write_event(Event::End(BytesEnd::new(section)))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    const VOID_NOOP_TEARDOWNS: [&str; 6] = [
        "ez_gfx_shader_destroy",
        "ez_gfx_counter_buffer_release",
        "ez_gfx_vertex_heap_destroy",
        "ez_gfx_buffer_release",
        "ez_gfx_texture_unload",
        "ez_gfx_render_target_destroy",
    ];
    /// Destroy exports that report typed teardown completion, including abandonment.
    const STATUS_TEARDOWNS: [&str; 2] = ["ez_gfx_context_destroy", "ez_gfx_surface_destroy"];

    fn assert_context_contract(function: &Decl, position: usize) {
        assert_eq!(position, 0, "{} must put context first", function.name);
        let parameter = &function.children[position];
        assert_eq!(
            parameter.attrs.get("type").map(String::as_str),
            Some("EzGfxContext"),
            "{} context has the wrong type",
            function.name
        );
        let no_op_teardown = VOID_NOOP_TEARDOWNS.contains(&function.name.as_str());
        let status_teardown = STATUS_TEARDOWNS.contains(&function.name.as_str());
        let returns_void = function.attrs.get("return").map(String::as_str) == Some("void");
        assert_eq!(
            returns_void, no_op_teardown,
            "{} has an unexpected context teardown contract",
            function.name
        );
        if status_teardown {
            assert_eq!(
                function.attrs.get("return").map(String::as_str),
                Some("EzGfxResult"),
                "{} must report typed teardown completion",
                function.name
            );
        }
        assert_eq!(
            parameter.attrs.get("nullable").map(String::as_str),
            Some(if no_op_teardown { "true" } else { "false" }),
            "{} context has the wrong nullability",
            function.name
        );
        assert!(
            !parameter.doc.trim().is_empty(),
            "{} context lacks documentation",
            function.name
        );
        if no_op_teardown {
            assert!(
                parameter.doc.contains("zero") && parameter.doc.contains("stale"),
                "{} context must document zero/stale no-op behavior",
                function.name
            );
        }
    }

    #[test]
    fn rejects_stale_metadata_items_and_children() {
        let mut metadata = Metadata::default();
        metadata
            .items
            .insert("struct:Removed".into(), MetaItem::default());
        assert!(validate_metadata(&metadata, &Contract::default()).is_err());

        let contract = parse_xml(header::DOC_XML).unwrap();
        let mut metadata = Metadata::default();
        for (kind, declarations) in [
            ("handle", contract.handles.as_slice()),
            ("enum", contract.enums.as_slice()),
            ("struct", contract.structs.as_slice()),
            ("function", contract.functions.as_slice()),
        ] {
            for declaration in declarations {
                metadata.items.insert(
                    format!("{kind}:{}", declaration.name),
                    MetaItem {
                        children: declaration
                            .children
                            .iter()
                            .map(|child| (child.name.clone(), BTreeMap::new()))
                            .collect(),
                        ..MetaItem::default()
                    },
                );
            }
        }
        metadata
            .items
            .get_mut("struct:EzGfxTestDesc")
            .unwrap()
            .children
            .insert("removed".into(), BTreeMap::new());
        assert!(validate_metadata(&metadata, &contract).is_err());
    }

    #[test]
    fn rejects_nonliteral_array_extent() {
        let ty: syn::Type = syn::parse_str("[u8; N]").unwrap();
        assert!(rust_field_type(&ty).is_err());
    }

    #[test]
    fn docs_stop_before_safety_contract() {
        let item: syn::ItemFn = syn::parse_quote! {
            /// Summary.
            ///
            /// # Safety
            /// Unsafe detail.
            fn f() {}
        };
        assert_eq!(docs(&item.attrs), "Summary.");
    }

    #[test]
    fn repository_contract_is_current_and_follows_abi_conventions() {
        let root = repository_root();
        let xml = generate_xml(&root).unwrap();
        assert_eq!(
            xml,
            fs::read_to_string(root.join("bindings/bindings.xml")).unwrap()
        );
        assert_eq!(
            generate_header(&xml).unwrap(),
            fs::read_to_string(root.join("bindings/c/include/ez_gfx_api.h")).unwrap()
        );

        let contract = parse_xml(&xml).unwrap();
        assert_eq!(contract.functions.len(), 61);
        for (name, parameters) in [
            ("ez_gfx_frame_bind", &["context", "frame", "binding"][..]),
            (
                "ez_gfx_frame_execute_compute",
                &[
                    "context",
                    "frame",
                    "shader",
                    "dispatch_x",
                    "dispatch_y",
                    "dispatch_z",
                ][..],
            ),
            (
                "ez_gfx_frame_execute_graphics",
                &["context", "frame", "shader", "buffer", "dynamic_state"][..],
            ),
            (
                "ez_gfx_value_buffer_acquire",
                &[
                    "context",
                    "value",
                    "value_size",
                    "debug_name",
                    "debug_name_length",
                    "out_buffer",
                ][..],
            ),
        ] {
            let function = contract
                .functions
                .iter()
                .find(|function| function.name == name)
                .unwrap_or_else(|| panic!("{name} is missing"));
            assert_eq!(
                function
                    .children
                    .iter()
                    .map(|parameter| parameter.name.as_str())
                    .collect::<Vec<_>>(),
                parameters
            );
        }
        for removed in [
            "ez_gfx_frame_add_compute_pipeline",
            "ez_gfx_frame_add_vertex_pipeline",
        ] {
            assert!(
                contract
                    .functions
                    .iter()
                    .all(|function| function.name != removed),
                "{removed} compatibility alias remains"
            );
        }

        for function in &contract.functions {
            let suffix = function.name.strip_prefix("ez_gfx_").unwrap();
            assert!(
                suffix.split('_').count() >= 2,
                "{} lacks object-operation naming",
                function.name
            );

            let context = function
                .children
                .iter()
                .position(|parameter| parameter.name == "context");
            if let Some(position) = context {
                assert_context_contract(function, position);
            }

            if !function.name.starts_with("ez_gfx_context_") {
                if let Some(second) = function.children.get(1) {
                    let second_type = second.attrs.get("type").map_or("", String::as_str);
                    if contract
                        .handles
                        .iter()
                        .any(|handle| handle.name == second_type)
                    {
                        let mut object = String::new();
                        for (index, character) in second_type
                            .strip_prefix("EzGfx")
                            .unwrap_or(second_type)
                            .chars()
                            .enumerate()
                        {
                            if character.is_ascii_uppercase() && index != 0 {
                                object.push('_');
                            }
                            object.push(character.to_ascii_lowercase());
                        }
                        let creates_named_object = function.children.iter().any(|parameter| {
                            parameter.name.strip_prefix("out_").is_some_and(|created| {
                                function.name.starts_with(&format!("ez_gfx_{created}_"))
                            })
                        });
                        if !creates_named_object {
                            assert!(
                                function.name.starts_with(&format!("ez_gfx_{object}_")),
                                "{} must name its second-argument {object} object",
                                function.name
                            );
                        }
                    }
                }
            }

            if let Some(position) = function
                .children
                .iter()
                .position(|parameter| parameter.name == "frame")
            {
                assert_eq!(context, Some(0), "{} frame lacks context", function.name);
                assert_eq!(position, 1, "{} must put frame second", function.name);
                assert!(
                    function.name.starts_with("ez_gfx_frame_"),
                    "{} uses non-frame terminology for a frame operation",
                    function.name
                );
            }
        }
    }
}
