[package]
name = "ez-gfx-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
basis = ["dep:basisu"]

[dependencies]
crossbeam-channel = "0.5"
parking_lot = "0.12"
rayon = "1.10"
basisu = { workspace = true, optional = true }

[lints]
workspace = true
