[package]
name = "ez-gfx-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true
ez-gfx-runtime.workspace = true
ez-gfx-artifact.workspace = true
ez-gfx-backend-vulkan = { path = "../ez-gfx-backend-vulkan" }

[target.'cfg(windows)'.dependencies]
ez-gfx-backend-dx12 = { path = "../ez-gfx-backend-dx12" }

[target.'cfg(target_vendor = "apple")'.dependencies]
ez-gfx-backend-metal = { path = "../ez-gfx-backend-metal" }

[dev-dependencies]
ez-gfx-compiler.workspace = true

[target.'cfg(target_vendor = "apple")'.dev-dependencies]
objc2.workspace = true
objc2-core-foundation.workspace = true
objc2-metal = { workspace = true, features = ["MTLTypes"] }
objc2-quartz-core.workspace = true
