[package]
name = "ez-gfx-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
basis = ["ez-gfx/basis"]
ktx2 = ["ez-gfx/ktx2"]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
ez-gfx = { workspace = true, features = ["ffi"] }
ez-gfx-core.workspace = true

[dev-dependencies]
ez-gfx-artifact.workspace = true
ez-gfx-compiler.workspace = true
ez-gfx-runtime.workspace = true


[target.'cfg(windows)'.dev-dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging"] }
[target.'cfg(target_vendor = "apple")'.dev-dependencies]
objc2.workspace = true
objc2-core-foundation.workspace = true
objc2-metal = { workspace = true, features = ["MTLTypes"] }
objc2-quartz-core.workspace = true

[lints]
workspace = true
