[package]
name = "ez-gfx-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
ez-gfx.workspace = true
ez-gfx-core.workspace = true

[dev-dependencies]
ez-gfx-artifact.workspace = true
ez-gfx-compiler.workspace = true

[target.'cfg(target_vendor = "apple")'.dev-dependencies]
objc2.workspace = true
objc2-core-foundation.workspace = true
objc2-metal = { workspace = true, features = ["MTLTypes"] }
objc2-quartz-core.workspace = true

[lints]
workspace = true
