[package]
name = "ez-gfx-backend-metal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ez-gfx-core.workspace = true
ez-gfx-hal.workspace = true
ez-gfx-runtime.workspace = true

[target.'cfg(target_vendor = "apple")'.dependencies]
objc2.workspace = true
objc2-metal = { workspace = true, features = ["dispatch2", "MTLAllocation", "MTLArgument", "MTLArgumentEncoder", "MTLBlitCommandEncoder", "MTLBuffer", "MTLCommandBuffer", "MTLCommandEncoder", "MTLCommandQueue", "MTLComputeCommandEncoder", "MTLComputePipeline", "MTLDepthStencil", "MTLDevice", "MTLDrawable", "MTLEvent", "MTLHeap", "MTLLibrary", "MTLRenderCommandEncoder", "MTLRenderPass", "MTLRenderPipeline", "MTLResource", "MTLSampler", "MTLTexture", "MTLTypes"] }
objc2-foundation.workspace = true
objc2-core-foundation.workspace = true
gpu-allocator = { workspace = true, features = ["std", "metal"] }
dispatch2.workspace = true
objc2-quartz-core.workspace = true

[target.'cfg(target_vendor = "apple")'.dev-dependencies]
ez-gfx-artifact.workspace = true
ez-gfx-compiler.workspace = true
ez-gfx-runtime.workspace = true
tempfile.workspace = true

[lints]
workspace = true
