[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
object = { version = "0.40", default-features = false, features = ["read", "std"] }
anyhow.workspace = true
clap.workspace = true
flate2 = "1.1"
sha2 = "0.10"
tar = "0.4"
walkdir = "2.5"
zip = { version = "4.3", default-features = false, features = ["deflate"] }


[lints]
workspace = true