/* Generated by tools/bindgen from bindings/bindings.xml. Do not edit; update crates/ez-gfx-ffi or tools/bindgen. */
#ifndef EZ_GFX_API_H
#define EZ_GFX_API_H

#include <stddef.h>
#include <stdint.h>

#define EZ_GFX_ABI_VERSION 40u

#if defined(__clang__)
#  if __has_attribute(access)
#    define EZ_GFX_ACCESS(...) __attribute__((access(__VA_ARGS__)))
#  else
#    define EZ_GFX_ACCESS(...)
#  endif
#elif defined(__GNUC__) && (__GNUC__ >= 10)
#  define EZ_GFX_ACCESS(...) __attribute__((access(__VA_ARGS__)))
#else
#  define EZ_GFX_ACCESS(...)
#endif

/* ABI string contract: each const char* has an explicit byte length, denotes exactly that many UTF-8 bytes without scanning for a terminator, and rejects embedded NUL. */

#ifdef __cplusplus
extern "C" {
#endif

/** Opaque packed `u64` context handle; slot+1/generation occupy bits 0-39. */
typedef uint64_t EzGfxContext;

/** Opaque packed `u64` surface handle; child bits index the context identity arena and resolve only as a surface. */
typedef uint64_t EzGfxSurface;

/** Opaque generation-, kind-, owner-, state-, and frame-serial-validated live frame handle. */
typedef uint64_t EzGfxFrame;

/** Stable process-unique identity for one enqueued readback request. */
typedef uint64_t EzGfxReadbackRequest;

/** Opaque context-owned compute shader handle. */
typedef uint64_t EzGfxComputeShader;

/** Opaque context-owned vertex shader handle. */
typedef uint64_t EzGfxVertexShader;

/** Opaque context-owned fragment shader handle. */
typedef uint64_t EzGfxFragmentShader;

/** Opaque packed `u64` one-frame counter-buffer handle; child bits resolve only as indirect commands. */
typedef uint64_t EzGfxCounterBuffer;

/** Opaque packed `u64` one-frame buffer handle; child bits resolve only as structured data. */
typedef uint64_t EzGfxBuffer;

/** Opaque named vertex heap whose owner and generation are validated. */
typedef uint64_t EzGfxVertexHeap;

/** Opaque allocation within a named vertex heap whose owner and generation are validated. */
typedef uint64_t EzGfxVertexAllocation;

/** Opaque allocation within the singleton index heap whose owner and generation are validated. */
typedef uint64_t EzGfxIndexAllocation;

/** Opaque packed `u64` texture handle; child bits index the context identity arena and resolve only as a texture. */
typedef uint64_t EzGfxTexture;

/** Opaque packed `u64` render-target handle; child bits index the context identity arena and resolve only as a render target. */
typedef uint64_t EzGfxRenderTarget;

/**
 * EzGfxResult:
 * @EzGfxResult_Ok: Operation completed successfully.
 * @EzGfxResult_InvalidArgument: An argument violates the operation contract.
 * @EzGfxResult_InvalidContext: A context or resource handle is invalid or stale.
 * @EzGfxResult_NativeFailure: The native graphics backend failed.
 * @EzGfxResult_NotReady: Completion or output is not yet available.
 * @EzGfxResult_Unsupported: The requested capability is unavailable.
 * @EzGfxResult_DeviceLost: The graphics device was lost.
 * @EzGfxResult_QueueFull: Asynchronous scheduling or staging capacity is unavailable.
 * @EzGfxResult_Cancelled: An asynchronous operation was cancelled before completion.
 * @EzGfxResult_TeardownAbandoned: Teardown completion is unproven; borrowed host handles must remain alive.
 *
 * Stable C ABI result code.
 */
typedef uint8_t EzGfxResult;
enum {
    EzGfxResult_Ok = 0,
    EzGfxResult_InvalidArgument = 1,
    EzGfxResult_InvalidContext = 2,
    EzGfxResult_NativeFailure = 3,
    EzGfxResult_NotReady = 4,
    EzGfxResult_Unsupported = 5,
    EzGfxResult_DeviceLost = 6,
    EzGfxResult_QueueFull = 7,
    EzGfxResult_Cancelled = 8,
    EzGfxResult_TeardownAbandoned = 9,
};

/**
 * EzGfxNativeWindowSystem:
 * @EzGfxNativeWindowSystem_Win32: Win32 HWND and HINSTANCE handles.
 * @EzGfxNativeWindowSystem_Xlib: Xlib Display pointer and Window XID.
 * @EzGfxNativeWindowSystem_Xcb: XCB connection pointer and window value.
 * @EzGfxNativeWindowSystem_Wayland: Wayland display and surface pointers.
 * @EzGfxNativeWindowSystem_AppKit: `AppKit` `NSView` pointer.
 *
 * Native window system selecting a portable window descriptor's handles.
 */
typedef uint8_t EzGfxNativeWindowSystem;
enum {
    EzGfxNativeWindowSystem_Win32 = 0,
    EzGfxNativeWindowSystem_Xlib = 1,
    EzGfxNativeWindowSystem_Xcb = 2,
    EzGfxNativeWindowSystem_Wayland = 3,
    EzGfxNativeWindowSystem_AppKit = 4,
};

/**
 * EzGfxTextureError:
 * @EzGfxTextureError_None: Indicates that no texture error occurred.
 * @EzGfxTextureError_InvalidContext: Indicates that the context identifier is invalid or stale.
 * @EzGfxTextureError_InvalidArguments: Indicates that one or more texture arguments are invalid.
 * @EzGfxTextureError_UnsupportedFormat: Indicates that the requested texture format cannot be used.
 * @EzGfxTextureError_OutOfTextureHandles: Indicates that no texture identifier slots remain.
 * @EzGfxTextureError_OutOfMemory: Indicates that texture allocation exhausted available memory.
 * @EzGfxTextureError_DecodeFailed: Indicates that the source image could not be decoded.
 * @EzGfxTextureError_VulkanFailed: Indicates that a Vulkan texture request failed.
 * @EzGfxTextureError_WorkerUnavailable: Indicates that no texture worker is available to process the request.
 * @EzGfxTextureError_NotFound: Indicates that the requested texture could not be found.
 *
 * C ABI result enumeration.
 */
typedef uint8_t EzGfxTextureError;
enum {
    EzGfxTextureError_None = 0,
    EzGfxTextureError_InvalidContext = 1,
    EzGfxTextureError_InvalidArguments = 2,
    EzGfxTextureError_UnsupportedFormat = 3,
    EzGfxTextureError_OutOfTextureHandles = 4,
    EzGfxTextureError_OutOfMemory = 5,
    EzGfxTextureError_DecodeFailed = 6,
    EzGfxTextureError_VulkanFailed = 7,
    EzGfxTextureError_WorkerUnavailable = 8,
    EzGfxTextureError_NotFound = 9,
};

/**
 * EzGfxAdapterClass:
 * @EzGfxAdapterClass_Software: Software renderer.
 * @EzGfxAdapterClass_Other: Adapter with no stronger classification.
 * @EzGfxAdapterClass_Integrated: Integrated GPU.
 * @EzGfxAdapterClass_Discrete: Discrete GPU.
 *
 * C ABI adapter classification; discriminants mirror core `AdapterClass`.
 */
typedef uint8_t EzGfxAdapterClass;
enum {
    EzGfxAdapterClass_Software = 0,
    EzGfxAdapterClass_Other = 1,
    EzGfxAdapterClass_Integrated = 2,
    EzGfxAdapterClass_Discrete = 3,
};

/**
 * EzGfxRenderTargetFormat:
 * @EzGfxRenderTargetFormat_Rgba8Unorm: Four-channel 8-bit normalized RGBA format.
 * @EzGfxRenderTargetFormat_Bgra8Srgb: Four-channel 8-bit sRGB BGRA format.
 * @EzGfxRenderTargetFormat_Rgba16Float: Four-channel 16-bit floating-point RGBA format.
 * @EzGfxRenderTargetFormat_Depth32Float: 32-bit floating-point depth format.
 * @EzGfxRenderTargetFormat_Bc7Unorm: BC7-compressed 8-bit normalized RGBA format.
 * @EzGfxRenderTargetFormat_Astc4x4Unorm: ASTC-compressed 4-by-4 texel 8-bit normalized RGBA format.
 *
 * C ABI render-target storage format; discriminants mirror runtime `Format`.
 */
typedef uint8_t EzGfxRenderTargetFormat;
enum {
    EzGfxRenderTargetFormat_Rgba8Unorm = 1,
    EzGfxRenderTargetFormat_Bgra8Srgb = 2,
    EzGfxRenderTargetFormat_Rgba16Float = 3,
    EzGfxRenderTargetFormat_Depth32Float = 4,
    EzGfxRenderTargetFormat_Bc7Unorm = 5,
    EzGfxRenderTargetFormat_Astc4x4Unorm = 6,
};

/**
 * EzGfxRenderTargetUsage:
 * @EzGfxRenderTargetUsage_Color: Supports color-rendering output.
 * @EzGfxRenderTargetUsage_Depth: Supports depth-rendering output; creation stays unsupported.
 * @EzGfxRenderTargetUsage_Storage: Supports storage access; creation stays unsupported.
 * @EzGfxRenderTargetUsage_Sampled: Supports texture sampling; creation stays unsupported.
 *
 * C ABI render-target access mode.
 */
typedef uint8_t EzGfxRenderTargetUsage;
enum {
    EzGfxRenderTargetUsage_Color = 0,
    EzGfxRenderTargetUsage_Depth = 1,
    EzGfxRenderTargetUsage_Storage = 2,
    EzGfxRenderTargetUsage_Sampled = 3,
};

/**
 * EzGfxEventKind:
 * @EzGfxEventKind_Upload: A typed upload state transition; `upload` is valid.
 * @EzGfxEventKind_Runtime: A runtime observation; `record` is valid.
 * @EzGfxEventKind_Diagnostic: A diagnostic observation; `record` and `level` are valid.
 * @EzGfxEventKind_ObservationsDropped: Bounded observability storage discarded records; `dropped` is valid.
 * @EzGfxEventKind_Readback: Completed explicitly requested readback bytes; the `readback_*` fields are valid.
 * @EzGfxEventKind_Snapshot: Unrequested persistent presentation snapshot; the `readback_*` fields are valid.
 *
 * Discriminates the payload carried by [`EzGfxEvent`].
 */
typedef uint8_t EzGfxEventKind;
enum {
    EzGfxEventKind_Upload = 1,
    EzGfxEventKind_Runtime = 2,
    EzGfxEventKind_Diagnostic = 3,
    EzGfxEventKind_ObservationsDropped = 4,
    EzGfxEventKind_Readback = 5,
    EzGfxEventKind_Snapshot = 6,
};

/**
 * EzGfxBackend:
 * @EzGfxBackend_Vulkan: Vulkan 1.3 backend.
 * @EzGfxBackend_Dx12: Direct3D 12 backend.
 * @EzGfxBackend_Metal: Metal backend.
 *
 * Selected native backend.
 */
typedef uint8_t EzGfxBackend;
enum {
    EzGfxBackend_Vulkan = 1,
    EzGfxBackend_Dx12 = 2,
    EzGfxBackend_Metal = 3,
};

/**
 * EzGfxPresentationMode:
 * @EzGfxPresentationMode_Fifo: Ordered, tear-free presentation at vertical blank.
 * @EzGfxPresentationMode_Mailbox: Newest-frame, tear-free presentation at vertical blank.
 * @EzGfxPresentationMode_Immediate: Unsynchronized presentation that may tear.
 * @EzGfxPresentationMode_Relaxed: Adaptive FIFO that may present immediately after a missed blank.
 * @EzGfxPresentationMode_Paced: Latest-ready, tear-free presentation at vertical blank.
 *
 * Requested swapchain presentation behavior.
 */
typedef uint8_t EzGfxPresentationMode;
enum {
    EzGfxPresentationMode_Fifo = 0,
    EzGfxPresentationMode_Mailbox = 1,
    EzGfxPresentationMode_Immediate = 2,
    EzGfxPresentationMode_Relaxed = 3,
    EzGfxPresentationMode_Paced = 4,
};

/**
 * EzGfxRuntimePhase:
 * @EzGfxRuntimePhase_Admission: Adapter or device admission.
 * @EzGfxRuntimePhase_Decode: Asset decoding.
 * @EzGfxRuntimePhase_Upload: Resource upload.
 * @EzGfxRuntimePhase_Bind: Resource binding.
 * @EzGfxRuntimePhase_Submit: Queue submission.
 * @EzGfxRuntimePhase_Present: Presentation.
 * @EzGfxRuntimePhase_Readback: GPU readback.
 * @EzGfxRuntimePhase_Device: Device lifecycle.
 *
 * Runtime operation phase.
 */
typedef uint8_t EzGfxRuntimePhase;
enum {
    EzGfxRuntimePhase_Admission = 1,
    EzGfxRuntimePhase_Decode = 2,
    EzGfxRuntimePhase_Upload = 3,
    EzGfxRuntimePhase_Bind = 4,
    EzGfxRuntimePhase_Submit = 5,
    EzGfxRuntimePhase_Present = 6,
    EzGfxRuntimePhase_Readback = 7,
    EzGfxRuntimePhase_Device = 8,
};

/**
 * EzGfxUploadResourceKind:
 * @EzGfxUploadResourceKind_Texture: Texture upload.
 * @EzGfxUploadResourceKind_VertexAllocation: Vertex allocation upload.
 * @EzGfxUploadResourceKind_IndexAllocation: Index allocation upload.
 *
 * Resource family carried by an upload event.
 */
typedef uint8_t EzGfxUploadResourceKind;
enum {
    EzGfxUploadResourceKind_Texture = 1,
    EzGfxUploadResourceKind_VertexAllocation = 2,
    EzGfxUploadResourceKind_IndexAllocation = 3,
};

/**
 * EzGfxUploadStatus:
 * @EzGfxUploadStatus_SourceStaged: Caller source bytes are no longer needed.
 * @EzGfxUploadStatus_DeviceReady: Resource is ready for rendering.
 * @EzGfxUploadStatus_Failed: Upload terminated with error.
 * @EzGfxUploadStatus_Cancelled: Upload was cancelled.
 *
 * Lossless upload transition.
 */
typedef uint8_t EzGfxUploadStatus;
enum {
    EzGfxUploadStatus_SourceStaged = 1,
    EzGfxUploadStatus_DeviceReady = 2,
    EzGfxUploadStatus_Failed = 3,
    EzGfxUploadStatus_Cancelled = 4,
};

/**
 * EzGfxDiagnosticLevel:
 * @EzGfxDiagnosticLevel_Info: Informational diagnostic.
 * @EzGfxDiagnosticLevel_Warning: Recoverable warning.
 * @EzGfxDiagnosticLevel_Error: Operation failure.
 *
 * Bounded local diagnostic severity.
 */
typedef uint8_t EzGfxDiagnosticLevel;
enum {
    EzGfxDiagnosticLevel_Info = 1,
    EzGfxDiagnosticLevel_Warning = 2,
    EzGfxDiagnosticLevel_Error = 3,
};

/**
 * EzGfxSourceTextureFormat:
 * @EzGfxSourceTextureFormat_Rgb: Raw RGB pixels.
 * @EzGfxSourceTextureFormat_Rgba: Raw RGBA pixels.
 * @EzGfxSourceTextureFormat_Bmp: BMP image bytes.
 * @EzGfxSourceTextureFormat_Jpeg: JPEG image bytes.
 * @EzGfxSourceTextureFormat_Png: PNG image bytes.
 * @EzGfxSourceTextureFormat_Tga: TGA image bytes.
 * @EzGfxSourceTextureFormat_Ktx2: KTX2 image bytes.
 * @EzGfxSourceTextureFormat_Basis: Optional standalone Basis Universal bytes.
 * @EzGfxSourceTextureFormat_Dds: DDS image bytes with a legacy or DX10 header.
 * @EzGfxSourceTextureFormat_Raw: Tightly packed mip bytes in the destination storage format.
 *
 * Source image encoding; values 128 through 255 are application decoders.
 */
typedef uint8_t EzGfxSourceTextureFormat;
enum {
    EzGfxSourceTextureFormat_Rgb = 0,
    EzGfxSourceTextureFormat_Rgba = 1,
    EzGfxSourceTextureFormat_Bmp = 2,
    EzGfxSourceTextureFormat_Jpeg = 3,
    EzGfxSourceTextureFormat_Png = 4,
    EzGfxSourceTextureFormat_Tga = 5,
    EzGfxSourceTextureFormat_Ktx2 = 6,
    EzGfxSourceTextureFormat_Basis = 7,
    EzGfxSourceTextureFormat_Dds = 8,
    EzGfxSourceTextureFormat_Raw = 9,
};

/**
 * EzGfxTextureFilter:
 * @EzGfxTextureFilter_Nearest: Nearest-neighbor filtering.
 * @EzGfxTextureFilter_Linear: Linear filtering.
 *
 * Texture sampling filter.
 */
typedef uint8_t EzGfxTextureFilter;
enum {
    EzGfxTextureFilter_Nearest = 0,
    EzGfxTextureFilter_Linear = 1,
};

/**
 * EzGfxTextureAddressMode:
 * @EzGfxTextureAddressMode_Repeat: Repeat coordinates.
 * @EzGfxTextureAddressMode_ClampToEdge: Clamp coordinates to the edge.
 *
 * Texture addressing mode.
 */
typedef uint8_t EzGfxTextureAddressMode;
enum {
    EzGfxTextureAddressMode_Repeat = 0,
    EzGfxTextureAddressMode_ClampToEdge = 1,
};

/**
 * EzGfxTextureDestinationFormat:
 * @EzGfxTextureDestinationFormat_Rgba8Unorm: Linear 8-bit normalized RGBA.
 * @EzGfxTextureDestinationFormat_Auto: Prefer admitted native compression.
 * @EzGfxTextureDestinationFormat_Rgba8Srgb: sRGB 8-bit normalized RGBA.
 * @EzGfxTextureDestinationFormat_Bc1Unorm: Linear BC1.
 * @EzGfxTextureDestinationFormat_Bc1Srgb: sRGB BC1.
 * @EzGfxTextureDestinationFormat_Bc3Unorm: Linear BC3.
 * @EzGfxTextureDestinationFormat_Bc3Srgb: sRGB BC3.
 * @EzGfxTextureDestinationFormat_Bc7Unorm: Linear BC7.
 * @EzGfxTextureDestinationFormat_Bc7Srgb: sRGB BC7.
 * @EzGfxTextureDestinationFormat_Astc4x4Unorm: Linear ASTC 4x4.
 * @EzGfxTextureDestinationFormat_Astc4x4Srgb: sRGB ASTC 4x4.
 *
 * Requested GPU texture storage.
 */
typedef uint8_t EzGfxTextureDestinationFormat;
enum {
    EzGfxTextureDestinationFormat_Rgba8Unorm = 0,
    EzGfxTextureDestinationFormat_Auto = 1,
    EzGfxTextureDestinationFormat_Rgba8Srgb = 2,
    EzGfxTextureDestinationFormat_Bc1Unorm = 3,
    EzGfxTextureDestinationFormat_Bc1Srgb = 4,
    EzGfxTextureDestinationFormat_Bc3Unorm = 5,
    EzGfxTextureDestinationFormat_Bc3Srgb = 6,
    EzGfxTextureDestinationFormat_Bc7Unorm = 7,
    EzGfxTextureDestinationFormat_Bc7Srgb = 8,
    EzGfxTextureDestinationFormat_Astc4x4Unorm = 9,
    EzGfxTextureDestinationFormat_Astc4x4Srgb = 10,
};

/**
 * EzGfxCullMode:
 * @EzGfxCullMode_None: No face culling.
 * @EzGfxCullMode_Front: Cull front-facing primitives.
 * @EzGfxCullMode_Back: Cull back-facing primitives.
 *
 * Pipeline cull mode.
 */
typedef uint8_t EzGfxCullMode;
enum {
    EzGfxCullMode_None = 0,
    EzGfxCullMode_Front = 1,
    EzGfxCullMode_Back = 2,
};

/**
 * EzGfxFrontFace:
 * @EzGfxFrontFace_CounterClockwise: Counter-clockwise winding.
 * @EzGfxFrontFace_Clockwise: Clockwise winding.
 *
 * Front-face winding order.
 */
typedef uint8_t EzGfxFrontFace;
enum {
    EzGfxFrontFace_CounterClockwise = 0,
    EzGfxFrontFace_Clockwise = 1,
};

/**
 * EzGfxPrimitiveType:
 * @EzGfxPrimitiveType_TriangleList: Triangle list.
 * @EzGfxPrimitiveType_PointList: Point list.
 * @EzGfxPrimitiveType_LineList: Line list.
 * @EzGfxPrimitiveType_LineStrip: Line strip.
 * @EzGfxPrimitiveType_TriangleStrip: Triangle strip.
 * @EzGfxPrimitiveType_TriangleFan: Triangle fan.
 *
 * Pipeline primitive topology.
 */
typedef uint8_t EzGfxPrimitiveType;
enum {
    EzGfxPrimitiveType_TriangleList = 0,
    EzGfxPrimitiveType_PointList = 1,
    EzGfxPrimitiveType_LineList = 2,
    EzGfxPrimitiveType_LineStrip = 3,
    EzGfxPrimitiveType_TriangleStrip = 4,
    EzGfxPrimitiveType_TriangleFan = 5,
};

/**
 * EzGfxBlendMode:
 * @EzGfxBlendMode_None: Opaque blending.
 * @EzGfxBlendMode_Alpha: Source-alpha blending.
 *
 * Pipeline blend mode.
 */
typedef uint8_t EzGfxBlendMode;
enum {
    EzGfxBlendMode_None = 0,
    EzGfxBlendMode_Alpha = 1,
};

/**
 * EzGfxPresentationModes:
 * @bits: Bits indexed by `EzGfxPresentationMode` values zero through four.
 *
 * Compact set of presentation modes available for one surface.
 */
typedef struct EzGfxPresentationModes {
    uint8_t bits;
} EzGfxPresentationModes;

/**
 * EzGfxAdapterDesc:
 * @stable_id: Stable 128-bit adapter identity from enumeration.
 * @allow_software: Whether a software-class adapter is acceptable; zero or one.
 *
 * Explicit adapter request selected by stable identity.
 */
typedef struct EzGfxAdapterDesc {
    uint8_t stable_id[16];
    uint8_t allow_software;
} EzGfxAdapterDesc;

/**
 * EzGfxAdapterInfo:
 * @stable_id: Stable 128-bit adapter identity from enumeration.
 * @backend: Backend code from `EzGfxBackend`.
 * @adapter_class: Class code from `EzGfxAdapterClass`.
 * @admitted: Whether the adapter passes admission under the queried policy; zero or one.
 * @software_rejected: Whether software policy alone rejects the adapter; zero or one.
 * @error_count: Count of unmet profile requirements; zero when admitted.
 *
 * Enumerated adapter identity with admission diagnostics under one software policy.
 */
typedef struct EzGfxAdapterInfo {
    uint8_t stable_id[16];
    EzGfxBackend backend;
    EzGfxAdapterClass adapter_class;
    uint8_t admitted;
    uint8_t software_rejected;
    uint32_t error_count;
} EzGfxAdapterInfo;

/**
 * EzGfxBackendContextDesc:
 * @enable_debug: Enables graphics-backend debugging when nonzero.
 * @enable_validation: Enables graphics API validation when nonzero.
 * @backend: Selects the graphics backend by its C ABI numeric code.
 * @texture_decode_workers: Async texture decode worker threads; zero selects the default topology.
 * @adapter_count: Explicit adapter requests; zero keeps default ranking, one selects by identity.
 * @adapter: Exactly `adapter_count` explicit requests; null if and only if zero.
 *
 * Describes graphics-context creation parameters with an explicit backend selector.
 */
typedef struct EzGfxBackendContextDesc {
    uint8_t enable_debug;
    uint8_t enable_validation;
    EzGfxBackend backend;
    uint32_t texture_decode_workers;
    uint32_t adapter_count;
    const EzGfxAdapterDesc * adapter;
} EzGfxBackendContextDesc;

/**
 * EzGfxWindowSurfaceDesc:
 * @system: Native window-system code from `EzGfxNativeWindowSystem`.
 * @cache_presented_snapshots: Enables caching of presented surface snapshots when nonzero.
 * @reserved: Must be zero.
 * @handle_a: First native handle slot; meaning follows `system`.
 * @handle_b: Second native handle slot; meaning follows `system`.
 *
 * Describes a portable native presentation window without a caller-supplied extent.
 */
typedef struct EzGfxWindowSurfaceDesc {
    EzGfxNativeWindowSystem system;
    uint8_t cache_presented_snapshots;
    uint8_t reserved[6];
    uint64_t handle_a;
    uint64_t handle_b;
} EzGfxWindowSurfaceDesc;

/**
 * EzGfxHeadlessSurfaceDesc:
 * @width: Specifies the initial surface width in pixels.
 * @height: Specifies the initial surface height in pixels.
 * @cache_presented_snapshots: Enables caching of rendered snapshots when nonzero.
 *
 * Describes a headless surface and its initial extent.
 */
typedef struct EzGfxHeadlessSurfaceDesc {
    uint32_t width;
    uint32_t height;
    uint8_t cache_presented_snapshots;
} EzGfxHeadlessSurfaceDesc;

/**
 * EzGfxTextureDesc:
 * @source_format: Identifies the source texel format by its C ABI numeric code.
 * @destination_format: Identifies the GPU destination format by its C ABI numeric code.
 * @width: Specifies the base mip level width in pixels.
 * @height: Specifies the base mip level height in pixels.
 * @mip_count: Specifies the number of mip levels in the texture.
 * @generate_mips: Requests automatic mip generation when nonzero.
 * @min_filter: Selects the minification filter by its C ABI numeric code.
 * @mag_filter: Selects the magnification filter by its C ABI numeric code.
 * @max_anisotropy: Specifies the maximum anisotropic filtering ratio.
 * @address_mode_u: Selects the texture-addressing mode for the U coordinate.
 * @address_mode_v: Selects the texture-addressing mode for the V coordinate.
 * @address_mode_w: Selects the texture-addressing mode for the W coordinate.
 * @debug_label: Points to exactly `debug_label_length` UTF-8 bytes when present.
 * @debug_label_length: Specifies the debug-label byte length, or zero when absent.
 *
 * Describes texture dimensions, formats, mipmapping, sampling, and labeling.
 */
typedef struct EzGfxTextureDesc {
    EzGfxSourceTextureFormat source_format;
    EzGfxTextureDestinationFormat destination_format;
    uint32_t width;
    uint32_t height;
    uint32_t mip_count;
    uint8_t generate_mips;
    EzGfxTextureFilter min_filter;
    EzGfxTextureFilter mag_filter;
    float max_anisotropy;
    EzGfxTextureAddressMode address_mode_u;
    EzGfxTextureAddressMode address_mode_v;
    EzGfxTextureAddressMode address_mode_w;
    const char * debug_label;
    size_t debug_label_length;
} EzGfxTextureDesc;

/**
 * EzGfxRenderTargetDesc:
 * @name: Points to exactly `name_length` UTF-8 bytes; required, 1..=255 bytes.
 * @name_length: Specifies the target-name byte length.
 * @usage: Selects the access mode by its C ABI numeric code.
 * @relative_scale: Scale factor relative to the reference dimensions; finite and positive.
 * @samples: Requested multisample count; one of 1, 2, 4, or 8.
 * @candidate_formats: Points to exactly `candidate_count` format codes; required, 1..=16 entries.
 * @candidate_count: Specifies the candidate format count.
 * @sampleable: Non-zero requires texture-sampling support; must be zero or one.
 * @use_clear: Non-zero stores `clear_color`; must be zero or one.
 * @clear_color: Color clear value read only when `use_clear` is non-zero.
 *
 * Describes render-target name, usage, format candidates, and clear value.
 */
typedef struct EzGfxRenderTargetDesc {
    const uint8_t * name;
    size_t name_length;
    EzGfxRenderTargetUsage usage;
    float relative_scale;
    uint8_t samples;
    const uint8_t * candidate_formats;
    uint32_t candidate_count;
    uint8_t sampleable;
    uint8_t use_clear;
    float clear_color[4];
} EzGfxRenderTargetDesc;

/**
 * EzGfxDecodedTextureMip:
 * @width: Mip width in texels.
 * @height: Mip height in texels.
 * @data: Readable bytes retained until the release callback.
 * @data_size: Exact byte length at `data`.
 *
 * Decoded bytes for one custom-decoder mip, retained until the release callback.
 */
typedef struct EzGfxDecodedTextureMip {
    uint32_t width;
    uint32_t height;
    const uint8_t * data;
    size_t data_size;
} EzGfxDecodedTextureMip;

/**
 * EzGfxDecodedTexture:
 * @format: Destination-format code; `Auto` is invalid for decoded output.
 * @mip_count: Number of entries at `mips`.
 * @mips: Readable array retained until the release callback.
 *
 * Custom-decoder output copied before its release callback is invoked.
 */
typedef struct EzGfxDecodedTexture {
    EzGfxTextureDestinationFormat format;
    uint32_t mip_count;
    const EzGfxDecodedTextureMip * mips;
} EzGfxDecodedTexture;

/**
 * EzGfxTextureRegionDesc:
 * @mip_level: Destination mip level.
 * @x: Destination X offset in texels.
 * @y: Destination Y offset in texels.
 * @width: Region width in texels.
 * @height: Region height in texels.
 * @data: Readable tightly packed texel or compressed-block bytes.
 * @data_size: Exact byte length at `data`.
 *
 * Borrowed bytes and destination rectangle for one asynchronous texture update.
 */
typedef struct EzGfxTextureRegionDesc {
    uint32_t mip_level;
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
    const uint8_t * data;
    size_t data_size;
} EzGfxTextureRegionDesc;

/**
 * EzGfxTextureUploadTelemetry:
 * @decode_microseconds: Aggregate CPU decode/transcode/mip-generation time.
 * @staging_bytes: Aggregate bytes admitted to native staging.
 * @queue_latency_microseconds: Aggregate transfer-owner queue latency.
 * @handoff_latency_microseconds: Aggregate transfer-to-graphics handoff latency.
 *
 * Monotonic context-wide asynchronous texture pipeline counters.
 */
typedef struct EzGfxTextureUploadTelemetry {
    uint64_t decode_microseconds;
    uint64_t staging_bytes;
    uint64_t queue_latency_microseconds;
    uint64_t handoff_latency_microseconds;
} EzGfxTextureUploadTelemetry;

/**
 * EzGfxResourceDiagnostics:
 * @pending_textures: Texture uploads awaiting decode or transfer completion.
 * @pending_texture_bytes: Admitted source bytes (decode) plus decoded staging bytes (transfer).
 * @pending_vertex_uploads: Vertex uploads awaiting transfer completion.
 * @pending_vertex_bytes: Vertex bytes awaiting transfer completion.
 * @pending_index_uploads: Index uploads awaiting transfer completion.
 * @pending_index_bytes: Index bytes awaiting transfer completion.
 * @staging_buckets: Staging buckets retained across the shared, buffer, and counter pools.
 * @staging_bytes: Staging bucket capacity retained across those pools.
 * @pipeline_entries: Compiled pipeline entries retained in the context cache.
 * @readback_bytes: Bytes retained across completed readback frames.
 *
 * Point-in-time pending-upload counts with retained bytes plus retained cache sizes.
 */
typedef struct EzGfxResourceDiagnostics {
    uint32_t pending_textures;
    uint64_t pending_texture_bytes;
    uint32_t pending_vertex_uploads;
    uint64_t pending_vertex_bytes;
    uint32_t pending_index_uploads;
    uint64_t pending_index_bytes;
    uint32_t staging_buckets;
    uint64_t staging_bytes;
    uint32_t pipeline_entries;
    uint64_t readback_bytes;
} EzGfxResourceDiagnostics;

/**
 * EzGfxBinding:
 * @name: Points to exactly `name_length` UTF-8 shader-binding-name bytes.
 * @name_length: Specifies the nonzero byte length available through `name`.
 * @buffer: Identifies the buffer assigned to the binding.
 * @counter_buffer: Identifies the counter command buffer assigned to the binding.
 * @render_target: Identifies the render target assigned to the binding.
 *
 * Associates a named shader binding with buffer and render-target resources.
 */
typedef struct EzGfxBinding {
    const char * name;
    size_t name_length;
    EzGfxBuffer buffer;
    EzGfxCounterBuffer counter_buffer;
    EzGfxRenderTarget render_target;
} EzGfxBinding;

/**
 * EzGfxDynamicState:
 * @cull_mode: Selects the polygon culling mode by its C ABI numeric code.
 * @front_face: Selects which vertex winding is considered front-facing.
 * @primitive_type: Selects the primitive topology by its C ABI numeric code.
 * @blend_mode: Selects the color blending mode by its C ABI numeric code.
 *
 * Encodes dynamic rasterization, topology, and blending state.
 */
typedef struct EzGfxDynamicState {
    EzGfxCullMode cull_mode;
    EzGfxFrontFace front_face;
    EzGfxPrimitiveType primitive_type;
    EzGfxBlendMode blend_mode;
} EzGfxDynamicState;

/**
 * EzGfxDrawIndexedCommand:
 * @index_count: Specifies the number of indices drawn per instance.
 * @instance_count: Specifies the number of instances to draw.
 * @first_index: Specifies the starting index within the index buffer.
 * @vertex_offset: Specifies the signed offset added to each fetched vertex index.
 * @first_instance: Specifies the first instance identifier used by the draw.
 *
 * Encodes one indexed, optionally instanced draw command.
 */
typedef struct EzGfxDrawIndexedCommand {
    uint32_t index_count;
    uint32_t instance_count;
    uint32_t first_index;
    int32_t vertex_offset;
    uint32_t first_instance;
} EzGfxDrawIndexedCommand;

/**
 * EzGfxByteBuffer:
 * @length: Specifies the byte count available through `data`.
 * @data: Points to the first byte of the range and may be null only when `length` is zero.
 *
 * Describes a contiguous read-only byte range across the C ABI.
 */
typedef struct EzGfxByteBuffer {
    size_t length;
    const uint8_t * data;
} EzGfxByteBuffer;

/**
 * EzGfxHandleParts:
 * @context_slot: Identifies the context slot in the context arena.
 * @context_generation: Records the generation of the context slot.
 * @child_slot: Identifies the child-resource slot within the context.
 * @child_generation: Records the generation of the child-resource slot.
 * @is_context: Is nonzero when the identifier refers directly to a context.
 * @_padding: Reserves bytes that keep the C ABI layout stable.
 *
 * Exposes the slot and generation components encoded in an opaque identifier.
 */
typedef struct EzGfxHandleParts {
    uint32_t context_slot;
    uint32_t context_generation;
    uint32_t child_slot;
    uint32_t child_generation;
    uint8_t is_context;
    uint8_t _padding[3];
} EzGfxHandleParts;

/**
 * EzGfxRuntimeRecord:
 * @correlation_id: Identifies the request or event associated with this record.
 * @resource: Identifies the graphics resource associated with this record.
 * @backend: Identifies the graphics backend by its C ABI numeric code.
 * @phase: Identifies the runtime phase by its C ABI numeric code.
 * @status: Identifies the phase status by its C ABI numeric code.
 * @_padding: Reserves bytes that keep the C ABI layout stable.
 *
 * Records correlated runtime progress for a graphics resource.
 */
typedef struct EzGfxRuntimeRecord {
    uint64_t correlation_id;
    uint64_t resource;
    EzGfxBackend backend;
    EzGfxRuntimePhase phase;
    EzGfxResult status;
    uint8_t _padding[5];
} EzGfxRuntimeRecord;

/**
 * EzGfxUploadEvent:
 * @resource: Opaque texture, vertex-allocation, or index-allocation handle.
 * @resource_kind: Resource kind: 1 texture, 2 vertex allocation, 3 index allocation.
 * @status: Status: 1 source staged, 2 device ready, 3 failed, 4 cancelled.
 * @error: `RuntimeStatus` code for failed events, zero otherwise.
 * @_padding: Reserves bytes that keep the C ABI layout stable.
 *
 * One lossless typed upload transition.
 */
typedef struct EzGfxUploadEvent {
    uint64_t resource;
    EzGfxUploadResourceKind resource_kind;
    EzGfxUploadStatus status;
    EzGfxResult error;
    uint8_t _padding[5];
} EzGfxUploadEvent;

/**
 * EzGfxDiagnostic:
 * @record: Contains the correlated runtime record being diagnosed.
 * @level: Identifies the diagnostic severity by its C ABI numeric code.
 * @_padding: Reserves bytes that keep the C ABI layout stable.
 *
 * Couples a runtime record with its diagnostic severity.
 */
typedef struct EzGfxDiagnostic {
    EzGfxRuntimeRecord record;
    EzGfxDiagnosticLevel level;
    uint8_t _padding[7];
} EzGfxDiagnostic;

/**
 * EzGfxEvent:
 * @kind: Selects the valid payload by its C ABI numeric code.
 * @_pad_kind: Reserves bytes that keep the C ABI layout stable.
 * @upload: Upload transition; valid when `kind` is `Upload`.
 * @record: Runtime or diagnostic record; valid when `kind` is `Runtime` or `Diagnostic`.
 * @level: Diagnostic severity; valid when `kind` is `Diagnostic`.
 * @_pad_level: Reserves bytes that keep the C ABI layout stable.
 * @dropped: Discarded-record count; valid when `kind` is `ObservationsDropped`.
 * @readback_request_id: Stable request correlator, or zero for an unrequested snapshot.
 * @readback_texture: Readback source texture, or zero for a surface-presented snapshot.
 * @readback_width: Readback image width in pixels; valid for `Readback` or `Snapshot`.
 * @readback_height: Readback image height in pixels; valid for `Readback` or `Snapshot`.
 * @readback_byte_count: Readback byte count; valid for `Readback` or `Snapshot`.
 * @readback_bytes: Readback RGBA bytes borrowed for this callback invocation only.
 *
 * One tagged graphics event delivered to the registered context callback. Only the payload selected by `kind` is valid. Readback bytes are borrowed for the callback invocation and must not be retained afterwards.
 */
typedef struct EzGfxEvent {
    EzGfxEventKind kind;
    uint8_t _pad_kind[7];
    EzGfxUploadEvent upload;
    EzGfxRuntimeRecord record;
    uint8_t level;
    uint8_t _pad_level[7];
    uint64_t dropped;
    EzGfxReadbackRequest readback_request_id;
    EzGfxTexture readback_texture;
    uint32_t readback_width;
    uint32_t readback_height;
    size_t readback_byte_count;
    const uint8_t * readback_bytes;
} EzGfxEvent;

/**
 * EzGfxContextDesc:
 * @enable_debug: Enables graphics-backend debugging when nonzero.
 * @enable_validation: Enables graphics API validation when nonzero.
 * @texture_decode_workers: Async texture decode worker threads; zero selects the default topology.
 * @adapter_count: Explicit adapter requests; zero keeps default ranking, one selects by identity.
 * @adapter: Exactly `adapter_count` explicit requests; null if and only if zero.
 *
 * Describes graphics-context creation parameters for the C ABI.
 */
typedef struct EzGfxContextDesc {
    uint8_t enable_debug;
    uint8_t enable_validation;
    uint32_t texture_decode_workers;
    uint32_t adapter_count;
    const EzGfxAdapterDesc * adapter;
} EzGfxContextDesc;

/** Custom image decoder invoked concurrently by texture workers. */
typedef EzGfxResult (*EzGfxTextureDecoderCallback)(const uint8_t * data, size_t data_size, uint8_t compression_support, EzGfxDecodedTexture * out_texture, void * user_data);

/** Releases a custom decoder result after ez-gfx copies every mip. */
typedef void (*EzGfxTextureDecoderReleaseCallback)(const EzGfxDecodedTexture * texture, void * user_data);

/** Context event callback invoked on the owner thread at graphics safe points. `event` borrows its payload, including readback bytes, for the invocation only. `user_data` is the registration value. Callbacks must not reenter graphics operations or unwind; a reentrant dispatch attempt fails and a panic unregisters the callback. */
typedef void (*EzGfxEventCallback)(const EzGfxEvent * event, void * user_data);

/**
 * ez_gfx_adapter_count:
 * @out_count: Receives the number of enumerated adapters.
 *
 * Returns the number of enumerated adapters without creating anything.
 *
 * Returns: Returns EzGfxResult_Ok or EzGfxResult_InvalidArgument.
 */
EzGfxResult ez_gfx_adapter_count(uint32_t * out_count) EZ_GFX_ACCESS(write_only, 1);

/**
 * ez_gfx_adapter_query:
 * @allow_software: Non-zero admits software-class adapters in the diagnosis; zero or one.
 * @out_adapters: Receives at most capacity entries; null if and only if capacity is zero.
 * @capacity: Writable entry count of out_adapters; zero queries the total with a null buffer.
 * @out_written: Receives entries written, or the total when capacity is zero.
 *
 * Enumerates adapters with admission diagnostics under one software policy. A zero capacity queries the total with a null buffer; otherwise the call fills at most `capacity` entries and reports how many it wrote. The `admitted`, `software_rejected`, and `error_count` fields diagnose each rejection without creating anything.
 */
EzGfxResult ez_gfx_adapter_query(uint8_t allow_software, EzGfxAdapterInfo * out_adapters, uint32_t capacity, uint32_t * out_written) EZ_GFX_ACCESS(write_only, 2, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_error_print:
 * @result: Result byte to describe; unknown values produce 'unknown error'.
 * @buffer: Caller-owned UTF-8 output; null only for a zero-capacity size query.
 * @capacity: Writable output bytes, or zero for a size query.
 * @out_required: Required bytes including the trailing NUL.
 *
 * Writes the stable UTF-8 message for an ABI result code. `out_required` receives the byte count including the trailing NUL. Pass a null buffer with zero capacity to query that count. Insufficient capacity returns `InvalidArgument` without modifying the buffer.
 *
 * Returns: Returns Ok, or InvalidArgument for an invalid pointer/capacity pair or insufficient storage.
 */
EzGfxResult ez_gfx_error_print(EzGfxResult result, char * buffer, size_t capacity, size_t * out_required) EZ_GFX_ACCESS(write_only, 2, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_vertex_heap_create:
 * @context: Owning initialized context.
 * @name: Exact UTF-8 heap-name bytes.
 * @name_length: Heap-name byte length.
 * @stride: Vertex stride.
 * @out_heap: Receives the heap handle.
 *
 * Creates a named vertex heap and returns its typed handle.
 *
 * Returns: Returns validation, allocation, or native status.
 */
EzGfxResult ez_gfx_vertex_heap_create(EzGfxContext context, const char * name, size_t name_length, uint64_t stride, EzGfxVertexHeap * out_heap) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(write_only, 5);

/**
 * ez_gfx_vertex_heap_destroy:
 * @context: Owning context; zero and stale values are ignored.
 * @heap: Vertex heap to destroy.
 *
 * Destroys the vertex heap selected by its typed handle.
 *
 * Returns: Stale and foreign handles are ignored.
 */
void ez_gfx_vertex_heap_destroy(EzGfxContext context, EzGfxVertexHeap heap);

/**
 * ez_gfx_index_allocation_create:
 * @context: Owning context.
 * @data: Packed uint32 index values.
 * @count: Index count.
 * @out_allocation: Receives the allocation handle.
 *
 * Uploads packed-u32 indices and returns a typed allocation handle.
 *
 * Returns: Returns upload or validation status.
 */
EzGfxResult ez_gfx_index_allocation_create(EzGfxContext context, const void * data, uint32_t count, EzGfxIndexAllocation * out_allocation) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_vertex_heap_upload:
 * @context: Owning context.
 * @heap: Owning vertex heap.
 * @data: Vertex bytes.
 * @element_count: Vertex count.
 * @element_size: Must equal heap stride.
 * @out_allocation: Receives the allocation handle.
 *
 * Uploads elements to a typed vertex heap and returns an allocation handle.
 *
 * Returns: Returns upload, ownership, or validation status.
 */
EzGfxResult ez_gfx_vertex_heap_upload(EzGfxContext context, EzGfxVertexHeap heap, const void * data, uint32_t element_count, uint64_t element_size, EzGfxVertexAllocation * out_allocation) EZ_GFX_ACCESS(read_only, 3, 4) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_vertex_allocation_get_range:
 * @context: Owning context.
 * @allocation: Vertex allocation.
 * @out_first: Receives first vertex.
 * @out_count: Receives vertex count.
 *
 * Queries a live vertex allocation range.
 *
 * Returns: Returns validation or ownership status.
 */
EzGfxResult ez_gfx_vertex_allocation_get_range(EzGfxContext context, EzGfxVertexAllocation allocation, uint32_t * out_first, uint32_t * out_count) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_index_allocation_get_range:
 * @context: Owning context.
 * @allocation: Index allocation.
 * @out_first: Receives first index.
 * @out_count: Receives index count.
 *
 * Queries a live index allocation range.
 *
 * Returns: Returns validation or ownership status.
 */
EzGfxResult ez_gfx_index_allocation_get_range(EzGfxContext context, EzGfxIndexAllocation allocation, uint32_t * out_first, uint32_t * out_count) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_vertex_allocation_remove:
 * @context: Owning context.
 * @allocation: Vertex allocation.
 *
 * Removes a live vertex allocation after establishing GPU safety.
 *
 * Returns: Returns validation or ownership status.
 */
EzGfxResult ez_gfx_vertex_allocation_remove(EzGfxContext context, EzGfxVertexAllocation allocation);

/**
 * ez_gfx_index_allocation_remove:
 * @context: Owning context.
 * @allocation: Index allocation.
 *
 * Removes a live index allocation after establishing GPU safety.
 *
 * Returns: Returns validation or ownership status.
 */
EzGfxResult ez_gfx_index_allocation_remove(EzGfxContext context, EzGfxIndexAllocation allocation);

/**
 * ez_gfx_buffer_acquire:
 * @context: Owning context.
 * @element_size: Element stride in bytes.
 * @element_count: Allocated element count.
 * @debug_name: Exact UTF-8 debug-name bytes.
 * @debug_name_length: Debug-name byte length.
 * @out_buffer: Receives the owning handle.
 *
 * Acquires a context-owned buffer sized for the requested elements.
 *
 * Returns: Returns validation or allocation status.
 */
EzGfxResult ez_gfx_buffer_acquire(EzGfxContext context, uint32_t element_size, uint32_t element_count, const char * debug_name, size_t debug_name_length, EzGfxBuffer * out_buffer) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_value_buffer_acquire:
 * @context: Owning context.
 * @value: Exact bytes of one value.
 * @value_size: Value byte size.
 * @debug_name: Exact UTF-8 debug-name bytes.
 * @debug_name_length: Debug-name byte length.
 * @out_buffer: Receives the initialized owning handle.
 *
 * Acquires a one-frame buffer initialized with exactly one value.
 *
 * Returns: Returns validation or allocation status.
 */
EzGfxResult ez_gfx_value_buffer_acquire(EzGfxContext context, const void * value, uint32_t value_size, const char * debug_name, size_t debug_name_length, EzGfxBuffer * out_buffer) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_buffer_write:
 * @context: Owning context.
 * @buffer: Unconsumed buffer handle.
 * @start_index: First destination element.
 * @data: Element bytes; null only when count is zero.
 * @element_count: Number of elements to copy.
 * @element_size: Must equal the acquired stride.
 *
 * Copies a typed element range into a buffer.
 *
 * Returns: Returns validation, ownership, or range status.
 */
EzGfxResult ez_gfx_buffer_write(EzGfxContext context, EzGfxBuffer buffer, uint32_t start_index, const void * data, uint32_t element_count, uint32_t element_size) EZ_GFX_ACCESS(read_only, 4, 5);

/**
 * ez_gfx_buffer_release:
 * @context: Owning context; zero and stale values are ignored.
 * @buffer: Buffer handle; zero and stale values are ignored.
 *
 * Releases a context-owned buffer handle; zero and stale values are ignored.
 *
 * Returns: Stale handles are ignored.
 */
void ez_gfx_buffer_release(EzGfxContext context, EzGfxBuffer buffer);

/**
 * ez_gfx_handle_inspect:
 * @handle: Packed handle to decode.
 * @out_parts: Receives context and optional child slot generations.
 *
 * Decodes a packed handle into its context and optional child slot generations.
 *
 * Returns: Returns EzGfxResult_Ok or a handle validation error.
 */
EzGfxResult ez_gfx_handle_inspect(uint64_t handle, EzGfxHandleParts * out_parts) EZ_GFX_ACCESS(write_only, 2);

/**
 * ez_gfx_semantic_id:
 * @name: Exact ASCII dot-separated name bytes; each non-empty segment starts with a letter and continues with letters, digits, or underscores; embedded NUL is invalid.
 * @length: Name byte count in the inclusive range 1..255.
 * @out_id: Receives exactly 16 identifier bytes.
 *
 * Computes the fixed-size identifier for a canonical semantic name.
 *
 * Returns: Returns EzGfxResult_Ok or EzGfxResult_InvalidArgument.
 */
EzGfxResult ez_gfx_semantic_id(const uint8_t * name, size_t length, uint8_t * out_id) EZ_GFX_ACCESS(read_only, 1, 2) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_abi_version:
 * Returns the C ABI revision supported by this library.
 *
 * Returns: ABI version; no context is required.
 */
uint32_t ez_gfx_abi_version(void);

/**
 * ez_gfx_context_create:
 * @desc: Context creation options.
 * @out_context: Receives the opaque context handle.
 *
 * Creates a graphics context from debug and validation options.
 *
 * Returns: Returns EzGfxResult_Ok or a creation error.
 */
EzGfxResult ez_gfx_context_create(const EzGfxContextDesc * desc, EzGfxContext * out_context) EZ_GFX_ACCESS(read_only, 1) EZ_GFX_ACCESS(write_only, 2);

/**
 * ez_gfx_context_create_backend:
 * @desc: Backend context options.
 * @out_context: Receives the opaque context handle.
 *
 * Creates a graphics context for Vulkan, Direct3D 12, or Metal.
 *
 * Returns: Returns EzGfxResult_Ok or a validation, admission, or native error.
 */
EzGfxResult ez_gfx_context_create_backend(const EzGfxBackendContextDesc * desc, EzGfxContext * out_context) EZ_GFX_ACCESS(read_only, 1) EZ_GFX_ACCESS(write_only, 2);

/**
 * ez_gfx_context_wait_idle:
 * @context: Owning context.
 *
 * Waits until all work submitted through the graphics context is idle, then delivers pending events.
 *
 * Returns: Returns EzGfxResult_Ok or an invalid-context, not-ready, native-failure, or device-loss result.
 */
EzGfxResult ez_gfx_context_wait_idle(EzGfxContext context);

/**
 * ez_gfx_context_destroy:
 * @context: Context to destroy on its creator thread; zero, stale, repeated, and wrong-thread calls report EzGfxResult_InvalidContext.
 *
 * Destroys the graphics context after aborting every live descendant frame. Reentrant entry or a boundary panic reports `TeardownAbandoned` because teardown completion is unproven.
 *
 * Returns: Returns EzGfxResult_Ok once teardown drains, EzGfxResult_InvalidContext for zero, stale, repeated, or wrong-thread handles, EzGfxResult_TeardownAbandoned when native completion is unproven or reentrant entry or a boundary panic prevents teardown, or another typed error only after terminal drained cleanup.
 */
EzGfxResult ez_gfx_context_destroy(EzGfxContext context);

/**
 * ez_gfx_context_register_callback:
 * @context: Owning context.
 * @callback: Callback to install; null clears the registration.
 * @user_data: Application state borrowed only during callback invocation.
 *
 * Replaces the context event callback and delivers pending events. A null callback clears the registration. Delivery runs on the calling owner thread inside this and other dispatching entry points, never on a worker thread. Callbacks must not reenter dispatching operations and must not unwind; a reentrant call fails and a panic unregisters the callback.
 *
 * Returns: Returns context, callback, or dispatch status.
 */
EzGfxResult ez_gfx_context_register_callback(EzGfxContext context, EzGfxEventCallback callback, void * user_data);

/**
 * ez_gfx_frame_begin:
 * @context: Owning context.
 * @surface: Surface to acquire.
 * @presentation_mode_code: Requested mode; deterministic fallback applies when unavailable.
 * @out_frame: Receives the live frame handle.
 *
 * Begins one surface frame and returns its explicit owner handle.
 *
 * Returns: Returns readiness or handle status.
 */
EzGfxResult ez_gfx_frame_begin(EzGfxContext context, EzGfxSurface surface, EzGfxPresentationMode presentation_mode_code, EzGfxFrame * out_frame) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_counter_buffer_acquire:
 * @context: Owning context.
 * @element_size: Element stride in bytes.
 * @element_count: Allocated element count.
 * @debug_name: Exact UTF-8 debug-name bytes.
 * @debug_name_length: Debug-name byte length.
 * @out_buffer: Receives the owning handle.
 *
 * Acquires a context-owned one-frame counter buffer with a runtime element stride.
 *
 * Returns: Returns validation or allocation status.
 */
EzGfxResult ez_gfx_counter_buffer_acquire(EzGfxContext context, uint32_t element_size, uint32_t element_count, const char * debug_name, size_t debug_name_length, EzGfxCounterBuffer * out_buffer) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_counter_buffer_write_draws:
 * @context: Owning context.
 * @buffer: Unconsumed counter buffer.
 * @start_index: First command slot.
 * @commands: Contiguous command data; null only when count is zero.
 * @command_count: Number of commands.
 *
 * Writes a contiguous indexed-draw command batch.
 *
 * Returns: Returns ownership, overflow, or bounds status.
 */
EzGfxResult ez_gfx_counter_buffer_write_draws(EzGfxContext context, EzGfxCounterBuffer buffer, uint32_t start_index, const EzGfxDrawIndexedCommand * commands, uint32_t command_count) EZ_GFX_ACCESS(read_only, 4, 5);

/**
 * ez_gfx_counter_buffer_publish_count:
 * @context: Owning context.
 * @buffer: Unconsumed counter buffer.
 * @count: Known generated-command count.
 *
 * Publishes a CPU-known count for compute-generated indirect commands.
 *
 * Returns: Returns ownership or bounds status.
 */
EzGfxResult ez_gfx_counter_buffer_publish_count(EzGfxContext context, EzGfxCounterBuffer buffer, uint32_t count);

/**
 * ez_gfx_counter_buffer_release:
 * @context: Owning context; zero and stale values are ignored.
 * @buffer: Counter buffer; zero and stale values are ignored.
 *
 * Releases an unconsumed counter buffer.
 *
 * Returns: No return value; stale and zero handles are ignored.
 */
void ez_gfx_counter_buffer_release(EzGfxContext context, EzGfxCounterBuffer buffer);

/**
 * ez_gfx_frame_bind:
 * @context: Owning context.
 * @frame: Live owning frame.
 * @binding: One named resource binding.
 *
 * Adds or replaces one named resource in the frame binding set.
 *
 * Returns: Returns validation, ownership, or frame status.
 */
EzGfxResult ez_gfx_frame_bind(EzGfxContext context, EzGfxFrame frame, const EzGfxBinding * binding) EZ_GFX_ACCESS(read_only, 3);

/**
 * ez_gfx_frame_execute_graphics:
 * @context: Owning context.
 * @frame: Live owning frame.
 * @vertex_shader: Vertex shader.
 * @fragment_shader: Fragment shader.
 * @buffer: Counter buffer containing indexed draw commands.
 * @dynamic_state: Optional dynamic pipeline state.
 *
 * Executes an indexed graphics operation from the current frame bindings.
 *
 * Returns: Returns validation or native status.
 */
EzGfxResult ez_gfx_frame_execute_graphics(EzGfxContext context, EzGfxFrame frame, EzGfxVertexShader vertex_shader, EzGfxFragmentShader fragment_shader, EzGfxCounterBuffer buffer, const EzGfxDynamicState * dynamic_state) EZ_GFX_ACCESS(read_only, 6);

/**
 * ez_gfx_frame_execute_compute:
 * @context: Owning context.
 * @frame: Live owning frame.
 * @shader: Compute shader.
 * @dispatch_x: X groups.
 * @dispatch_y: Y groups.
 * @dispatch_z: Z groups.
 *
 * Executes a compute dispatch from the current frame bindings.
 *
 * Returns: Returns validation or native status.
 */
EzGfxResult ez_gfx_frame_execute_compute(EzGfxContext context, EzGfxFrame frame, EzGfxComputeShader shader, uint32_t dispatch_x, uint32_t dispatch_y, uint32_t dispatch_z);

/**
 * ez_gfx_frame_enqueue_texture_readback:
 * @context: Owning context.
 * @frame: Live owning frame.
 * @texture: Texture to read back.
 * @out_request_id: Receives the stable request correlator.
 *
 * Enqueues a texture readback and returns its stable callback correlator.
 *
 * Returns: Returns frame, handle, or output-pointer status.
 */
EzGfxResult ez_gfx_frame_enqueue_texture_readback(EzGfxContext context, EzGfxFrame frame, EzGfxTexture texture, EzGfxReadbackRequest * out_request_id) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_frame_end:
 * @context: Owning context.
 * @frame: Live frame to consume.
 *
 * Consumes and completes a frame; every result invalidates the handle. Queued upload, runtime, and diagnostic events dispatch before ordered requested readbacks. Persistent presentation captures are trailing `Snapshot` events with request ID zero.
 *
 * Returns: Returns submission or presentation status; every result invalidates the handle.
 */
EzGfxResult ez_gfx_frame_end(EzGfxContext context, EzGfxFrame frame);

/**
 * ez_gfx_frame_abort:
 * @context: Owning context.
 * @frame: Live frame to abort.
 *
 * Consumes a frame without submitting; every result invalidates the handle.
 *
 * Returns: Returns abort status; every result invalidates the handle.
 */
EzGfxResult ez_gfx_frame_abort(EzGfxContext context, EzGfxFrame frame);

/**
 * ez_gfx_surface_create_window:
 * @context: Context that owns the surface.
 * @desc: Portable tagged native window handles; no caller extent. After device initialization, host-managed or undefined Vulkan extents require ez_gfx_surface_resize with the current host framebuffer extent before the first frame.
 * @out_surface: Receives the opaque surface handle.
 *
 * Creates a native window presentation surface and returns its handle. After device initialization, host-managed or undefined Vulkan extents require one `ez_gfx_surface_resize` with the current host framebuffer extent before the first frame.
 *
 * Returns: Returns EzGfxResult_Ok, EzGfxResult_TeardownAbandoned when failed post-native publication cannot prove surface release, or a validation/native error.
 */
EzGfxResult ez_gfx_surface_create_window(EzGfxContext context, const EzGfxWindowSurfaceDesc * desc, EzGfxSurface * out_surface) EZ_GFX_ACCESS(read_only, 2) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_surface_create_headless:
 * @context: Context that owns the surface.
 * @desc: Headless extent and snapshot policy.
 * @out_surface: Receives the opaque surface handle.
 *
 * Creates a headless surface and returns its handle.
 *
 * Returns: Returns EzGfxResult_Ok or a validation/native error.
 */
EzGfxResult ez_gfx_surface_create_headless(EzGfxContext context, const EzGfxHeadlessSurfaceDesc * desc, EzGfxSurface * out_surface) EZ_GFX_ACCESS(read_only, 2) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_context_init_device:
 * @context: Owning context.
 * @surface: Surface owned by context. Host-managed or undefined Vulkan extents require an initial host resize after successful initialization.
 *
 * Initializes the context device for the specified presentation surface. A successful window initialization with a host-managed or undefined Vulkan extent remains unready until `ez_gfx_surface_resize` publishes the current host framebuffer extent.
 *
 * Returns: Returns EzGfxResult_Ok or a native failure.
 */
EzGfxResult ez_gfx_context_init_device(EzGfxContext context, EzGfxSurface surface);

/**
 * ez_gfx_surface_resize:
 * @context: Owning context.
 * @surface: Surface to resize or initialize with a host-managed framebuffer extent.
 * @width: New width; zero is valid only with zero height for minimized state.
 * @height: New height; zero is valid only with zero width for minimized state.
 *
 * Requests new pixel dimensions and publishes host-managed window extents for a presentation surface.
 *
 * Returns: Returns EzGfxResult_Ok, EzGfxResult_NotReady, or an error.
 */
EzGfxResult ez_gfx_surface_resize(EzGfxContext context, EzGfxSurface surface, uint32_t width, uint32_t height);

/**
 * ez_gfx_surface_get_extent:
 * @context: Owning context.
 * @surface: Surface to query.
 * @out_width: Receives width.
 * @out_height: Receives height.
 *
 * Queries the current width and height of a presentation surface.
 *
 * Returns: Returns EzGfxResult_NotReady while minimized.
 */
EzGfxResult ez_gfx_surface_get_extent(EzGfxContext context, EzGfxSurface surface, uint32_t * out_width, uint32_t * out_height) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_surface_get_presentation_modes:
 * @context: Owning context.
 * @surface: Surface to query.
 * @out_modes: Receives bits indexed by EzGfxPresentationMode.
 *
 * Queries the compact presentation-mode set available for a surface.
 *
 * Returns: Returns query or handle status.
 */
EzGfxResult ez_gfx_surface_get_presentation_modes(EzGfxContext context, EzGfxSurface surface, EzGfxPresentationModes * out_modes) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_surface_resize_pending:
 * @context: Owning context.
 * @surface: Surface to query.
 * @out_pending: Receives 0 or 1.
 *
 * Reports whether a presentation-surface resize remains pending.
 *
 * Returns: Returns EzGfxResult_Ok or an error.
 */
EzGfxResult ez_gfx_surface_resize_pending(EzGfxContext context, EzGfxSurface surface, int32_t * out_pending) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_surface_set_snapshot_cache:
 * @context: Owning context.
 * @surface: Surface to configure.
 * @enabled: Must be zero or one.
 *
 * Enables or disables caching of presented snapshots for a surface.
 *
 * Returns: Returns EzGfxResult_Ok or a validation error.
 */
EzGfxResult ez_gfx_surface_set_snapshot_cache(EzGfxContext context, EzGfxSurface surface, int32_t enabled);

/**
 * ez_gfx_surface_destroy:
 * @context: Owning context; zero, stale, and wrong-thread handles report EzGfxResult_InvalidContext.
 * @surface: Surface to destroy; zero, stale, foreign, and repeated handles report EzGfxResult_InvalidContext.
 *
 * Destroys a presentation surface owned by the context.
 *
 * Returns: Returns EzGfxResult_Ok once teardown drains, EzGfxResult_InvalidContext for zero, stale, foreign, repeated, or wrong-thread handles, EzGfxResult_TeardownAbandoned when submitted native work cannot be proven complete, or another typed backend result.
 */
EzGfxResult ez_gfx_surface_destroy(EzGfxContext context, EzGfxSurface surface);

/**
 * ez_gfx_render_target_create:
 * @context: Owning context.
 * @desc: Target name, usage, candidates, and clear value.
 * @width: Target width in pixels.
 * @height: Target height in pixels.
 * @out_target: Receives the opaque render-target handle.
 *
 * Creates a managed render target from a declaration and explicit extents. Depth, storage, and sampled-only declarations stay unsupported with explicit errors; multisampled color declarations allocate render storage that resolves into the sampled image. The target leases one heap slot from the
 *
 * Returns: Returns Ok, Unsupported for depth/storage/multisample, or validation/native status.
 */
EzGfxResult ez_gfx_render_target_create(EzGfxContext context, const EzGfxRenderTargetDesc * desc, uint32_t width, uint32_t height, EzGfxRenderTarget * out_target) EZ_GFX_ACCESS(read_only, 2) EZ_GFX_ACCESS(write_only, 5);

/**
 * ez_gfx_render_target_destroy:
 * @context: Owning context; zero and stale values are ignored.
 * @target: Render target to destroy.
 *
 * Destroys a render target and clears any bound override; stale handles are ignored.
 *
 * Returns: No return value; null or stale handles are ignored.
 */
void ez_gfx_render_target_destroy(EzGfxContext context, EzGfxRenderTarget target);

/**
 * ez_gfx_render_target_get_format:
 * @context: Owning context.
 * @target: Render target to query.
 * @out_format: Receives the format code from EzGfxRenderTargetFormat.
 *
 * Reports the resolved storage format code of a live render target.
 *
 * Returns: Returns EzGfxResult_Ok or a validation or handle status.
 */
EzGfxResult ez_gfx_render_target_get_format(EzGfxContext context, EzGfxRenderTarget target, uint8_t * out_format) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_render_target_get_extent:
 * @context: Owning context.
 * @target: Render target to query.
 * @out_width: Receives width in pixels.
 * @out_height: Receives height in pixels.
 *
 * Reports the extents of a live render target.
 *
 * Returns: Returns EzGfxResult_Ok or a validation or handle status.
 */
EzGfxResult ez_gfx_render_target_get_extent(EzGfxContext context, EzGfxRenderTarget target, uint32_t * out_width, uint32_t * out_height) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_render_target_get_clear:
 * @context: Owning context.
 * @target: Render target to query.
 * @out_use_clear: Receives zero or one.
 * @out_color: Receives four color components; zeros when no clear is stored.
 *
 * Reports the stored clear value of a live render target. Writes one zero-or-one flag plus four color components (`[0, 0, 0, 0]` when no clear is stored).
 *
 * Returns: Returns EzGfxResult_Ok or a validation or handle status.
 */
EzGfxResult ez_gfx_render_target_get_clear(EzGfxContext context, EzGfxRenderTarget target, uint8_t * out_use_clear, float * out_color) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_render_target_probe_format:
 * @context: Owning context.
 * @format: Format code from EzGfxRenderTargetFormat.
 * @samples: Requested multisample count; one of 1, 2, 4, or 8.
 *
 * Probes whether one format admits a sampled color target at the given sample count. The status is the answer: `Ok` when resolvable, `Unsupported` otherwise. Depth, storage, and above-ceiling sample requests stay unsupported with explicit errors.
 *
 * Returns: Returns Ok when resolvable, Unsupported otherwise, or validation status.
 */
EzGfxResult ez_gfx_render_target_probe_format(EzGfxContext context, uint8_t format, uint8_t samples);

/**
 * ez_gfx_render_target_frame_begin:
 * @context: Owning context.
 * @target: Render target to render into.
 * @out_frame: Receives the live frame handle.
 *
 * Begins one render-target frame and returns its explicit owner handle.
 *
 * Returns: Returns state, handle, or capability status.
 */
EzGfxResult ez_gfx_render_target_frame_begin(EzGfxContext context, EzGfxRenderTarget target, EzGfxFrame * out_frame) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_compute_shader_load:
 * @context: Owning context.
 * @data: Validated artifact bytes.
 * @data_size: Artifact byte count.
 * @entry_point: Exact UTF-8 entry-point name.
 * @entry_point_size: Entry-point byte count.
 * @out_shader: Receives the owning compute shader handle.
 *
 * Loads one exact compute entry point from a validated artifact.
 *
 * Returns: Returns EzGfxResult_Ok or validation/native failure.
 */
EzGfxResult ez_gfx_compute_shader_load(EzGfxContext context, const uint8_t * data, size_t data_size, const char * entry_point, size_t entry_point_size, EzGfxComputeShader * out_shader) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_vertex_shader_load:
 * @context: Owning context.
 * @data: Validated artifact bytes.
 * @data_size: Artifact byte count.
 * @entry_point: Exact UTF-8 entry-point name.
 * @entry_point_size: Entry-point byte count.
 * @out_shader: Receives the owning vertex shader handle.
 *
 * Loads one exact vertex entry point from a validated artifact.
 *
 * Returns: Returns EzGfxResult_Ok or validation/native failure.
 */
EzGfxResult ez_gfx_vertex_shader_load(EzGfxContext context, const uint8_t * data, size_t data_size, const char * entry_point, size_t entry_point_size, EzGfxVertexShader * out_shader) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_fragment_shader_load:
 * @context: Owning context.
 * @data: Validated artifact bytes.
 * @data_size: Artifact byte count.
 * @entry_point: Exact UTF-8 entry-point name.
 * @entry_point_size: Entry-point byte count.
 * @out_shader: Receives the owning fragment shader handle.
 *
 * Loads one exact fragment entry point from a validated artifact.
 *
 * Returns: Returns EzGfxResult_Ok or validation/native failure.
 */
EzGfxResult ez_gfx_fragment_shader_load(EzGfxContext context, const uint8_t * data, size_t data_size, const char * entry_point, size_t entry_point_size, EzGfxFragmentShader * out_shader) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(read_only, 4, 5) EZ_GFX_ACCESS(write_only, 6);

/**
 * ez_gfx_compute_shader_destroy:
 * @context: Owning context; zero and stale values are ignored.
 * @shader: Compute shader to destroy.
 *
 * Invalidates immediately. An active frame retains its record through its terminal operation.
 *
 * Returns: No return value; stale handles are ignored.
 */
void ez_gfx_compute_shader_destroy(EzGfxContext context, EzGfxComputeShader shader);

/**
 * ez_gfx_vertex_shader_destroy:
 * @context: Owning context; zero and stale values are ignored.
 * @shader: Vertex shader to destroy.
 *
 * Invalidates immediately. An active frame retains its record through its terminal operation.
 *
 * Returns: No return value; stale handles are ignored.
 */
void ez_gfx_vertex_shader_destroy(EzGfxContext context, EzGfxVertexShader shader);

/**
 * ez_gfx_fragment_shader_destroy:
 * @context: Owning context; zero and stale values are ignored.
 * @shader: Fragment shader to destroy.
 *
 * Invalidates immediately. An active frame retains its record through its terminal operation.
 *
 * Returns: No return value; stale handles are ignored.
 */
void ez_gfx_fragment_shader_destroy(EzGfxContext context, EzGfxFragmentShader shader);

/**
 * ez_gfx_texture_decoder_register:
 * @source_format: Custom source code.
 * @callback: Concurrent decode callback.
 * @release: Successful-output release callback.
 * @user_data: Application state retained through unregister and accepted work.
 *
 * Registers one application decoder for a custom source code in `128..=255`. The callback may run concurrently. Successful output is copied and then released exactly once.
 *
 * Returns: Returns Ok or InvalidArgument.
 */
EzGfxResult ez_gfx_texture_decoder_register(EzGfxSourceTextureFormat source_format, EzGfxTextureDecoderCallback callback, EzGfxTextureDecoderReleaseCallback release, void * user_data);

/**
 * ez_gfx_texture_decoder_unregister:
 * @source_format: Custom source code.
 *
 * Unregisters one custom source decoder. Accepted requests retain their callback.
 *
 * Returns: Returns Ok or InvalidArgument.
 */
EzGfxResult ez_gfx_texture_decoder_unregister(EzGfxSourceTextureFormat source_format);

/**
 * ez_gfx_texture_load:
 * @context: Owning context.
 * @data: Encoded or raw image bytes.
 * @data_size: Input byte count.
 * @desc: Texture decode and sampling description.
 * @out_texture: Receives opaque texture handle.
 *
 * Loads texture bytes, configures sampling and mip residency, and returns a texture handle.
 *
 * Returns: Returns queueing, validation, decode, or support status.
 */
EzGfxResult ez_gfx_texture_load(EzGfxContext context, const uint8_t * data, size_t data_size, const EzGfxTextureDesc * desc, EzGfxTexture * out_texture) EZ_GFX_ACCESS(read_only, 2, 3) EZ_GFX_ACCESS(read_only, 4) EZ_GFX_ACCESS(write_only, 5);

/**
 * ez_gfx_texture_cancel:
 * @context: Owning context.
 * @texture: Texture request handle.
 *
 * Cancels a texture request before native transfer submission.
 *
 * Returns: Returns Ok when cancellation wins, or InvalidArgument for a terminal or stale request.
 */
EzGfxResult ez_gfx_texture_cancel(EzGfxContext context, EzGfxTexture texture);

/**
 * ez_gfx_texture_get_binding:
 * @context: Owning context.
 * @texture: Texture handle.
 * @out_binding: Receives binding index.
 *
 * Queries the binding index assigned to a loaded texture.
 *
 * Returns: Returns EzGfxResult_NotReady while upload remains in flight.
 */
EzGfxResult ez_gfx_texture_get_binding(EzGfxContext context, EzGfxTexture texture, uint32_t * out_binding) EZ_GFX_ACCESS(write_only, 3);

/**
 * ez_gfx_texture_get_residency:
 * @context: Owning context.
 * @texture: Texture handle.
 * @out_resident_mips: Receives completed mip count, possibly zero while uploads are pending.
 * @out_total_mips: Receives immutable decoded mip count.
 *
 * Queries the resident and total mip counts for a loaded texture.
 *
 * Returns: Returns EzGfxResult_Ok or a validation or handle status.
 */
EzGfxResult ez_gfx_texture_get_residency(EzGfxContext context, EzGfxTexture texture, uint32_t * out_resident_mips, uint32_t * out_total_mips) EZ_GFX_ACCESS(write_only, 3) EZ_GFX_ACCESS(write_only, 4);

/**
 * ez_gfx_texture_set_residency:
 * @context: Owning context.
 * @texture: Texture handle.
 * @resident_mips: Requested contiguous coarse mip count.
 *
 * Sets the contiguous coarse mip count exposed through the stable texture binding.
 *
 * Returns: Returns Ok when published, NotReady while uploads or safe descriptor rewrites remain pending, or a validation or handle status.
 */
EzGfxResult ez_gfx_texture_set_residency(EzGfxContext context, EzGfxTexture texture, uint32_t resident_mips);

/**
 * ez_gfx_texture_update_region:
 * @context: Owning context.
 * @texture: Resident texture handle.
 * @desc: Region and borrowed input bytes.
 *
 * Copies and asynchronously uploads one validated texture sub-rectangle.
 *
 * Returns: Returns Ok on admission, QueueFull when scheduling or staging capacity is unavailable, or validation/native status.
 */
EzGfxResult ez_gfx_texture_update_region(EzGfxContext context, EzGfxTexture texture, const EzGfxTextureRegionDesc * desc) EZ_GFX_ACCESS(read_only, 3);

/**
 * ez_gfx_texture_get_upload_telemetry:
 * @context: Owning context.
 * @out_telemetry: Receives a coherent counter snapshot.
 *
 * Returns a snapshot of monotonic context-wide texture upload counters.
 *
 * Returns: Returns Ok or context/device status.
 */
EzGfxResult ez_gfx_texture_get_upload_telemetry(EzGfxContext context, EzGfxTextureUploadTelemetry * out_telemetry) EZ_GFX_ACCESS(write_only, 2);

/**
 * ez_gfx_context_get_resource_diagnostics:
 * @context: Owning context.
 * @out_diagnostics: Receives pending counts with retained bytes plus retained cache sizes.
 *
 * Returns pending-upload counts with retained bytes plus retained cache sizes.
 *
 * Returns: Returns Ok or context status.
 */
EzGfxResult ez_gfx_context_get_resource_diagnostics(EzGfxContext context, EzGfxResourceDiagnostics * out_diagnostics) EZ_GFX_ACCESS(write_only, 2);

/**
 * ez_gfx_texture_unload:
 * @context: Owning context; zero and stale values are ignored.
 * @texture: Texture handle.
 *
 * Unloads a texture from the context.
 *
 * Returns: No return value; null or stale handles are ignored.
 */
void ez_gfx_texture_unload(EzGfxContext context, EzGfxTexture texture);

#ifdef __cplusplus
}
#endif

#endif
